import streamlit as st
import pandas as pd
from datetime import datetime
import io
import re
import copy
from fpdf import FPDF
from PIL import Image

try:
    from streamlit_option_menu import option_menu
except ImportError:
    st.error("Adicione 'streamlit-option-menu' no requirements.txt")

try:
    from st_aggrid import AgGrid, GridOptionsBuilder
    HAS_AGGRID = True
except ImportError:
    HAS_AGGRID = False

try:
    import plotly.express as px
    import plotly.graph_objects as go
    HAS_PLOTLY = True
except ImportError:
    HAS_PLOTLY = False

try:
    from supabase import create_client, Client
    HAS_SUPABASE = True
except ImportError:
    HAS_SUPABASE = False

try:
    import pytesseract
    HAS_OCR = True
except ImportError:
    HAS_OCR = False

# Importação da Inteligência Artificial do Google
try:
    import google.generativeai as genai
    HAS_GEMINI = True
except ImportError:
    HAS_GEMINI = False

# ==========================================
# CONFIGURAÇÃO E TEMA GOV.BR / ENTERPRISE
# ==========================================
st.set_page_config(page_title="Fiscalização GGTAB", page_icon="🚭", layout="wide")

def aplicar_tema_institucional():
    st.markdown("""
        <style>
        #MainMenu {visibility: hidden;}
        footer {visibility: hidden;}
        header {visibility: hidden;}
        
        .gov-header {
            background-color: #0A3B7C;
            padding: 10px 20px;
            color: #FFFFFF !important;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            font-size: 14px;
            font-weight: 600;
            border-bottom: 4px solid #00A859;
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            z-index: 999999;
            display: flex;
            align-items: center;
            box-shadow: 0 2px 4px rgba(0,0,0,0.5);
        }
        
        .block-container { padding-top: 5rem !important; }
        
        button[kind="primary"] {
            background-color: #0A3B7C !important;
            color: #FFFFFF !important;
            border-radius: 8px !important;
            border: none !important;
            box-shadow: 0 4px 6px rgba(0,0,0,0.2) !important;
        }
        button[kind="primary"]:hover { background-color: #0050A0 !important; }
        button[kind="secondary"] { border-radius: 8px !important; border: 1px solid #0A3B7C !important; }
        
        .stTextInput>div>div>input, .stNumberInput>div>div>input { border-radius: 6px !important; }
        .stTextInput>div>div>input:focus, .stNumberInput>div>div>input:focus {
            border-color: #0A3B7C !important; box-shadow: 0 0 0 1px #0A3B7C !important;
        }
        div[data-testid="stExpander"] { border-radius: 8px; border: 1px solid var(--border-color); }
        .streamlit-expanderHeader { font-weight: 600 !important; }
        </style>
        
        <div class="gov-header">
            🇧🇷 REPÚBLICA FEDERATIVA DO BRASIL | MINISTÉRIO DA SAÚDE - ANVISA (GGTAB)
        </div>
    """, unsafe_allow_html=True)

aplicar_tema_institucional()

# ==========================================
# CONEXÃO SUPABASE & AUDITORIA
# ==========================================
@st.cache_resource
def init_supabase():
    if not HAS_SUPABASE: return None
    try:
        return create_client(st.secrets["SUPABASE_URL"], st.secrets["SUPABASE_KEY"])
    except Exception: return None

supabase_client = init_supabase()

def registrar_log(acao, detalhes):
    if supabase_client and st.session_state.get('nome_fiscal'):
        try:
            supabase_client.table("auditoria").insert({
                "data_hora": datetime.now().isoformat(),
                "fiscal": st.session_state['nome_fiscal'],
                "acao": acao,
                "detalhes": detalhes
            }).execute()
        except Exception: pass

# ==========================================
# BASE DE DADOS COMPLETA E CORRIGIDA
# ==========================================
DB_PRODUTOS_BASE = {
    "💨 DEF (Dispositivos Eletrônicos para Fumar)": {
        "Cigarros eletrônicos (Vapes e Pods)": {
            "Ignite (Pod Descartável)": "Ilegal/Sem CNPJ",
            "Elfbar (Pod Descartável)": "Ilegal/Sem CNPJ",
            "Waka (Pod Descartável)": "Ilegal/Sem CNPJ",
            "Lost Mary (Pod Descartável)": "Ilegal/Sem CNPJ",
            "NikBar (Pod Descartável)": "Ilegal/Sem CNPJ",
            "Life Pod": "Ilegal/Sem CNPJ",
            "Vaporesso (Aparelho/Mod)": "Ilegal/Sem CNPJ",
            "Smok (Aparelho/Mod)": "Ilegal/Sem CNPJ",
            "Voopoo (Aparelho/Mod)": "Ilegal/Sem CNPJ",
            "Geekvape (Aparelho/Mod)": "Ilegal/Sem CNPJ",
            "Uwell / Caliburn": "Ilegal/Sem CNPJ"
        },
        "Cigarros aquecidos ou tabaco aquecido": {
            "IQOS (Heets / Terea)": "Ilegal/Sem CNPJ",
            "Glo (Neo)": "Ilegal/Sem CNPJ",
            "Ploom (Evo)": "Ilegal/Sem CNPJ",
            "Jouz": "Ilegal/Sem CNPJ"
        },
        "Vaporizadores de ervas secas": {
            "G Pen (Grenco Science)": "Ilegal/Sem CNPJ",
            "Pax (Pax Labs)": "Ilegal/Sem CNPJ",
            "Mighty / Volcano (Storz & Bickel)": "Ilegal/Sem CNPJ",
            "Dynavap": "Ilegal/Sem CNPJ",
            "Zigg (King Vapo)": "Ilegal/Sem CNPJ",
            "Arizer": "Ilegal/Sem CNPJ"
        },
        "Produtos híbridos": {
            "Lil Solid (KT&G)": "Ilegal/Sem CNPJ",
            "Ploom Tech": "Ilegal/Sem CNPJ"
        },
        "Essências e Juices (Líquidos para DEF)": {
            "Nasty Juice": "Ilegal/Sem CNPJ",
            "Naked 100": "Ilegal/Sem CNPJ",
            "Zomo Vape (Juice)": "Ilegal/Sem CNPJ",
            "Magna": "Ilegal/Sem CNPJ",
            "BLVK Unicorn": "Ilegal/Sem CNPJ",
            "Dinner Lady": "Ilegal/Sem CNPJ",
            "Caravela Liquids": "Ilegal/Sem CNPJ"
        }
    },
    "🍂 TABACOS E DERIVADOS": {
        "🚬 Cigarros (Filtro/Kretek)": {
            "GRIFFE BLUE (BRIX SPECIAL TABACO BLEND LTDA)": "27.643.835/0001-16",
            "EL CRETEC CHERRY (CLEAN INDUSTRIA E COMERCIO DE CIGARROS LTDA)": "18.804.581/0001-80",
            "CLEAN CLK (CLEAN INDUSTRIA E COMERCIO DE CIGARROS LTDA)": "18.804.581/0001-80",
            "EL CRETEC MENTHOL (CLEAN INDUSTRIA E COMERCIO DE CIGARROS LTDA)": "18.804.581/0001-80",
            "EL PONCIO CRETEC CEREJA (CLEAN INDUSTRIA E COMERCIO DE CIGARROS LTDA)": "18.804.581/0001-80",
            "EL PONCIO CRETEC MENTA (CLEAN INDUSTRIA E COMERCIO DE CIGARROS LTDA)": "18.804.581/0001-80",
            "EL PONCIO GUDANG GARAM RED (CLEAN INDUSTRIA E COMERCIO DE CIGARROS LTDA)": "18.804.581/0001-80",
            "EL PONCIO GUDANG GARAM GREEN (CLEAN INDUSTRIA E COMERCIO DE CIGARROS LTDA)": "18.804.581/0001-80",
            "A2 (CONGO INDUSTRIA E COMERCIO DE CIGARROS IMPORTACAO E EXPORTACAO LTDA)": "12.011.627/0001-27",
            "LE7 (CONGO INDUSTRIA E COMERCIO DE CIGARROS IMPORTACAO E EXPORTACAO LTDA)": "12.011.627/0001-27",
            "NEW YORK (CONGO INDUSTRIA E COMERCIO DE CIGARROS IMPORTACAO E EXPORTACAO LTDA)": "12.011.627/0001-27",
            "SENAT (CONGO INDUSTRIA E COMERCIO DE CIGARROS IMPORTACAO E EXPORTACAO LTDA)": "12.011.627/0001-27",
            "EXPRESS SAN MARINO BLUE (DICINA IND. E COM., IMP. E EXP. DE TABACOS LTDA)": "10.742.854/0001-05",
            "EXPRESS SAN MARINO RED (DICINA IND. E COM., IMP. E EXP. DE TABACOS LTDA)": "10.742.854/0001-05",
            "OSCAR CLASSIC TRADITIONAL (DICINA IND. E COM., IMP. E EXP. DE TABACOS LTDA)": "10.742.854/0001-05",
            "VILA RICA SKY (DICINA IND. E COM., IMP. E EXP. DE TABACOS LTDA)": "10.742.854/0001-05",
            "VILA RICA SUN (DICINA IND. E COM., IMP. E EXP. DE TABACOS LTDA)": "10.742.854/0001-05",
            "XES ORIGINAL (DICINA IND. E COM., IMP. E EXP. DE TABACOS LTDA)": "10.742.854/0001-05",
            "X-LINT WHITE (DICINA IND. E COM., IMP. E EXP. DE TABACOS LTDA)": "10.742.854/0001-05",
            "BILLION (EBT - EMPRESA BRASILEIRA DE TABACO LTDA)": "44.133.360/0001-37",
            "WINDSOR (EBT - EMPRESA BRASILEIRA DE TABACO LTDA)": "44.133.360/0001-37",
            "EGIPT BLUE (IBC – INDÚSTRIA BRASILEIRA DE CIGARROS LTDA)": "20.901.675/0001-19",
            "EGIPT RED (IBC – INDÚSTRIA BRASILEIRA DE CIGARROS LTDA)": "20.901.675/0001-19",
            "US FOX BLUE (IBC – INDÚSTRIA BRASILEIRA DE CIGARROS LTDA)": "20.901.675/0001-19",
            "CAMEL BLUE INTERNATIONAL SINCE 1913 (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL COMPACT (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL COMPACT BLUE PREMIUM BLEND (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL COMPACT PEAR (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL KRETEK BERRY (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL KRETEK MENTHOL (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL DOUBLE MINT & RED (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL LEGEND BLUE (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL LEGEND YELLOW (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL MY BLUE (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL MY YELLOW (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL PURPLE BEACH (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL PURBLE BEACH X (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL RED DUNE (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL RED DUNE X (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL YELLOW INTERNATIONAL SINCE 1913 (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL YELLOW TROPICAL (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL YELLOW TROPICAL X (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "DJARUM BLACK ICE (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "DJARUM BLACK JADE MENTHOL (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "DJARUM BLACK ORIGINAL (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "LA MENTHOL (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON AVANT XS BLUE (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON BLUE HAND SELECTED TOBACCO (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON BLUE SELECTED (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON CLASSIC HAND SELECTED TOBACCO (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON CLASSIC SELECTED (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON SELECT PURPLE MINT (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON SELECTED DOUBLE MENTHOL (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON SELECTED BLUEMIX (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON SELECTED PURPLEMIX (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON SLIMS RED (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON SILVER SELECTED (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON UNIQUE RED (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON XSTYLE BLUE (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON XSTYLE CASTER (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON XSTYLE RED (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON XSTYLE SILVER (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "A SAMPOERNA KRETEK MENTHOL SELECT KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "A SAMPOERNA KRETEK MENTHOL SELECTED KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "A SAMPOERNA KRETEK SELECTED KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD ORIGINAL BLUE KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD ORIGINAL LABEL KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD REMIX BEATS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD REMIX FRESH MINT KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD REMIX SELECT (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD REMIX WILD (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD SILVER KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD TERRAS BRASILEIRAS SELECIONADO (ORANGE) (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD TERRAS BRASILEIRAS ORIGINAL AZUL (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD TERRAS BRASILEIRAS ORIGINAL LARANJA (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD TERRAS BRASILEIRAS SELECIONADO (BLUE) (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD TERRAS BRASILEIRAS SELECIONADO (SILVER) (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD TERRAS BRASILEIRAS TABACO SELECIONADO BLUE (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD TERRAS BRASILEIRAS TABACO SELECIONADO ORIGINAL (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "HARMONY SELECIONADO BY LINEA (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "HARMONY SLIMS BY LUXOR (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "L&M BLUE LINE KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "L&M EVO KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "L&M FIRST CUT (BLUE) (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "L&M FIRST CUT (BLUE) TOBACCO (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "L&M FIRST CUT (RED) (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "L&M FIRST CUT (RED) TOBACCO (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "L&M FIRST CUT (SILVER) (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "L&M FORWARD (NEW BLACK) KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "L&M KRETEK (BLACK) KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO ADVANCE (BLACK) KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO ADVANCE FOREST (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO ADVANCE TROPICAL (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO BLUE SELECTION EST° 1908 (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO FILTER PLUS KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO FOREST FUSION (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO GOLD SELECTION EST° 1908 (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO GOLD (STRIPES) KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO ICE BURST MENTHOL KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO KRETEK MINT (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO (RED FWD) KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO RED SELECTION ESTº 1908 KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO SELECTION FOREST BREEZE ESTº 1908 (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO TROPICAL FUSION (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO VISTA DOUBLE BURST (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO VISTA DOUBLE FUSION (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO VISTA PURPLE MIX - (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "PRIORI (PRIORI TABACOS INDÚSTRIA E COMÉRCIO LTDA)": "34.593.307/0001-65",
            "GIFT (QUALITY IN TABACOS IND. E COM. DE CIGARROS E IMPORTAÇÃO E EXPORTAÇÃO LTDA)": "11.816.308/0001-26",
            "GIFT RED SECOND EDITION (QUALITY IN TABACOS IND. E COM. DE CIGARROS E IMPORTAÇÃO E EXPORTAÇÃO LTDA)": "11.816.308/0001-26",
            "NEW OUTBACK SLIMS (QUALITY IN TABACOS IND. E COM. DE CIGARROS E IMPORTAÇÃO E EXPORTAÇÃO LTDA)": "11.816.308/0001-26",
            "DUNHILL BLUE BLEND 2.0 (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL CARLTON BLEND 2.0 (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL DOUBLE REFRESH (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL ICE REFRESH (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL INSIGNIA BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL INSIGNIA FULL RED (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL INSIGNIA RED (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL ON BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL ON ICE BOOST (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL ON ICE TROPIC (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL ON RED (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL ON SILVER (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL ST JAMES ST LONDON BLUE BLEND (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL ST JAMES ST LONDON CARLTON BLEND (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL TOBACCO OF LONDON LTD EST 1907 EVOQUE TABACO BLEND (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL VOYAGE DOUBLE REFRESH (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL VOYAGE ICE REFRESH (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL VOYAGE MIX REFRESH (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "HOLLYWOOD CORE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "HOLLYWOOD CORE BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "KENT BLUE SERIES (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "KENT MIX GREEN TWIST (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "KENT MIX PURPLE TWIST (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "KENT MIX RED TWIST (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "KENT PRO BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "KENT PRO RED (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "KENT PRO SILVER (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "KENT RED SERIES (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "KENT SILVER SERIES (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE AN AMERICAN ORIGINAL (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE BLUE AN AMERICAN ORIGINAL (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE BLUE BLEND LUCKIES SINCE 1871 (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE BLUE CLICK (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE BLUE R.A. PATTERSON FOUNDER ESTD 1871 (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE DOUBLE CLICK (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE DOUBLE FROST (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE FRESH DOUBLE ICE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE FRESH DOUBLE ICE X (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE FRESH ICE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE FRESH MINT X (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE FRESH WILD (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE ORIGINAL BLEND LUCKIES SINCE 1871 (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE PURPLE MIX (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE RED MIX (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE RED R.A. PATTERSON FOUNDER ESTD 1871 (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE TWIST MIX (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE WILD MIX (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS GLOBAL CONNECTIONS BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS GLOBAL CONNECTIONS SILVER (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON EST. 1890 LOUIS ROTHMAN ORIGINAL TOBACCO GLOBAL BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON EST. 1890 LOUIS ROTHMAN ORIGINAL TOBACCO GLOBAL RED (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 BLUE INTERNATIONAL (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 GLOBAL BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 GLOBAL RED (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 HAND-SELECTED TOBACCOS BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 HAND-SELECTED TOBACCOS CORE BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 HAND-SELECTED TOBACCOS KINGSIZE BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 HAND-SELECTED TOBACCOS KINGSIZE RED (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 HAND-SELECTED TOBACCOS KINGSIZE SILVER (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 HAND-SELECTED TOBACCOS RED (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 HAND-SELECTED TOBACCOS SILVER (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 ICE BOOST (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 INTERNATIONAL WORLDWIDE CLICK SENSE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 INTERNATIONAL WORLDWIDE DOUBLE CLICK (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 PURPLE BOOST (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 SENSES FRESH (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 SPHERE BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 TROPICAL BOOST (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 WHITE CLASSIC BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 WHITE CLASSIC RED (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON CORE BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON SERIES BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON SERIES CLICK PURPLE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON SERIES RED (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON SIGNATURE BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "GF (VITORIA IMPORTAÇÃO, EXPORTAÇÃO, INDUSTRIA & COMERCIO DE TABACOS LTDA)": "18.559.637/0001-88",
            "WORLD STOP (VITORIA IMPORTAÇÃO, EXPORTAÇÃO, INDUSTRIA & COMERCIO DE TABACOS LTDA)": "18.559.637/0001-88"
        },
        "🕴️ Charutos": {
            "LOS 3 CATEDRATICOS DELÍCIAS ROBUSTO (ALCEMIRO FERREIRA DE BARROS - ME)": "12.791.254/0001-54",
            "PERCEVERANCIA NICARAGUA - TORO (APM COMERCIO, IMPORTAÇÃO E EXPORTAÇÃO DE FUMO LTDA)": "05.968.360/0001-03",
            "ARTURO FUENTE CHATEAU FUENTE (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "ARTURO FUENTE MAGNUM R VITOLA FIFTY-SIX (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "BRICK HOUSE TORO (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "FACTORY SMOKES ROBUSTO (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "JOYA DE NICARAGUA ANTAÑO CT TORO (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "JOYA DE NICARAGUA ANTAÑO CONSUL (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "JOYA DE NICARAGUA CABINETTA ROBUSTO (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "JOYA DE NICARAGUA CLASSICO ORIGINAL ROBUSTO (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "JOYA DE NICARAGUA MEDIO SIGLO TORO (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "NUB CONNECTICUT 460 (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "OLIVA SERIE G AGED CAMEROON DOUBLE ROBUSTO (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "OLIVIA SERIE V DOUBLE TORO (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "OLIVA SERIE V MELANIO Nº4 (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "PERLA DEL MAR ROBUSTO (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "QUORUM ROBUSTO (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "ROSALONES RESERVA R50 (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "GENTILI (CRISTINA D'ANGELO - COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO LTDA)": "40.585.474/0001-67",
            "PICHARDO RESERVA FAMILIAR SAN ANDRÉS (EDUARDO LLERENA HERNANDEZ)": "12.470.901/0001-26",
            "FLOR DE LA VEGA (BRAVOS-TORO) (E & M INTERNATIONAL IMPORTACAO E EXPORTACAO DE PRODUTOS DE TABACARIA LTDA ME)": "10.375.124/0001-05",
            "LEITE E ALVES ROBUSTO (FÁBRICA DE CHARUTOS LEITE E ALVES LTDA – ME)": "07.362.838/0001-74",
            "DON FERNANDO EXIGENTES (F E BENCOMO PEREZ ARTIGOS DE TABACARIA)": "08.890.797/0001-51",
            "7 PONTAS (HAVANA INDUSTRIA E COMÉRCIO DE FUMOS LIMITADA - ME)": "76.865.187/0001-58",
            "CARAVANA (HAVANA INDUSTRIA E COMÉRCIO DE FUMOS LIMITADA - ME)": "76.865.187/0001-58",
            "TALVIS CORONA (INDUSTRIA TABACOS DA BAHIA LTDA)": "05.816.263/0001-97",
            "LA CUBANITA (J&B IMPORTAÇÃO E EXPORTAÇÃO LTDA)": "32.340.714/0001-35",
            "JAMM CIGAR SUPER PREMIUM (JAMM CIGAR CHARUTOS LTDA)": "39.960.144/0001-25",
            "DON JORGE ROBUSTO (JORGE ESPINOSA CASTELLANOS LTDA)": "38.306.405/0001-25",
            "COHIBA ROBUSTO (MAREVA COMERCIALIZAÇÃO DE TABACO ME)": "25.370.137/0001-69",
            "LA GLORIA CUBANA (MAREVA COMERCIALIZAÇÃO DE TABACO ME)": "25.370.137/0001-69",
            "MONTECRISTO N. 4 (MAREVA COMERCIALIZAÇÃO DE TABACO ME)": "25.370.137/0001-69",
            "PARTAGAS SERIE D N.4 (MAREVA COMERCIALIZAÇÃO DE TABACO ME)": "25.370.137/0001-69",
            "ROMEO Y JULIETA MILLE FLEURS (MAREVA COMERCIALIZAÇÃO DE TABACO ME)": "25.370.137/0001-69",
            "CAFÉ CRÈME GRANDE I (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "CAFÉ CRÈME GRANDE II (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "CAO PILON ROBUSTO (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "DON DIEGO ROBUSTO (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "MACANUDO INSPIRADO (WHITE) ROBUSTO (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "PHILLIES TITAN (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "PHILLIES TITAN CHOCOLATE (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "PHILLIES TITAN PINK (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "REPOSADO 96 ESTATE BLEND ROBUSTO (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "VEGAFINA 1998 LA ROMANA 50 (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "VEGAFINA ROBUSTO (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "VDG SUMATRA Nº2 CLARO (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "SAN RAFFAEL CORONA (SAN GENARO INDUSTRIA E COMERCIO LTDA)": "23.664.538/0001-04",
            "SECONDS TORO (STJA GRAN HABANO CHARUTARIA LTDA)": "26.652.153/0001-07",
            "DON EMMANUEL ANUNNAKI KI (ZIGURATE IMPORTACAO E DISTRIBUICAO LTDA)": "52.126.566/0001-68",
            "DON BLEND GENIALES (Y.R. HERNANDEZ COMÉRCIO DE CHARUTOS - ME)": "23.159.448/0001-58"
        },
        "🌿 Fumo Desfiado": {
            "MIRAGE WHITE CREAM (BANES TABACOS & CO LTDA)": "59.212.133/0001-74",
            "TABEAR (BEAR OFFICIAL TABACOS LTDA)": "26.622.376/0001-21",
            "FUMO DESFIADO BELA FLOR (BELA FLOR INDUSTRIA E COMERCIO DE FUMOS LTDA)": "88.654.827/0001-60",
            "FUMOS LUAR (BELA FLOR INDUSTRIA E COMERCIO DE FUMOS LTDA)": "88.654.827/0001-60",
            "FUMO DESFIADO BOMBACO TRADICIONAL (BOMBACO PRODUTOS DE TABACO LTDA)": "35.472.366/0001-48",
            "STECKER AMARELINHO (COMERCIAL DE FUMOS BLEND LTDA)": "05.476.749/0001-23",
            "XORORÓ (COMERCIO E INDÚSTRIA DE FUMO ARAPIRACA LTDA – EPP)": "53.671.251/0001-64",
            "FUMO DESFIADO JURITI (COMÉRCIO E INDÚSTRIA DE FUMOS JAUENSE LTDA)": "55.817.217/0001-80",
            "CATOINHO (DISTRIBUIDORA DE FUMOS CATOINHO LTDA)": "55.428.288/0001-91",
            "DUBLIN ICE MINT TOBACCO (DUBLIN TABACOS LTDA)": "37.391.845/0001-65",
            "ZOMO (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "ALÍAR (HOPPE INDÚSTRIA E COMÉRCIO DE TABACOS LTDA)": "15.698.792/0001-97",
            "AMSTERDAM (HOPPE INDÚSTRIA E COMÉRCIO DE TABACOS LTDA)": "15.698.792/0001-97",
            "ACREMA BLEND (HBT INDÚSTRIA E COMÉRCIO DE TABACOS LTDA)": "18.044.630/0001-23",
            "HI TOBACCO GOLDEN VIRGINIA (HBT INDÚSTRIA E COMÉRCIO DE TABACOS LTDA)": "18.044.630/0001-23",
            "HI TOBACCO VIRGINIA BLEND (HBT INDÚSTRIA E COMÉRCIO DE TABACOS LTDA)": "18.044.630/0001-23",
            "RAINBOW GOLDEN BROWN (HBT INDÚSTRIA E COMÉRCIO DE TABACOS LTDA)": "18.044.630/0001-23",
            "RAINBOW SILVER BRIGHT (HBT INDÚSTRIA E COMÉRCIO DE TABACOS LTDA)": "18.044.630/0001-23",
            "TABAQUIN GOLDEN VIRGINIA (HBT INDÚSTRIA E COMÉRCIO DE TABACOS LTDA)": "18.044.630/0001-23",
            "FUMO DESFIADO BF (INDUSTRIA E COMERCIO DE FUMOS BEIJA FLOR LTDA)": "88.617.899/0001-37",
            "FUMO WILSON (INDÚSTRIA E COMÉRCIO DE FUMOS JATAI LTDA)": "01.693.647/0001-09",
            "FUMO SUPER GALO (INDUSTRIA E COMERCIO DE FUMOS SUPER GALO LTDA - EPP)": "05.418.580/0001-55",
            "REI DO ORIENTE MÉDIO (JOSÉ GILMAR MICHELS & CIA LTDA)": "89.461.131/0001-80",
            "ZEBÚ (JOSÉ GILMAR MICHELS & CIA LTDA)": "89.461.131/0001-80",
            "AMERICAN SPIRIT BLUE RYO (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "LA REVOLUCIÓN GOLDEN VIRGINIA (LRV BRASIL INDÚSTRIA E COMERCIO E EXPORTAÇÃO DE TABACO LTDA)": "33.377.413/0001-49",
            "SLC DE OURO (MARCELO CERENTINI)": "17.425.086/0001-05",
            "TAHAS (NELMARA PORTO PREBIANCHI)": "42.819.542/0001-30",
            "JUNGLE BAUNILHA (NORTE PIONEIRO INDÚSTRIA E COMÉRCIO DE FUMOS EIRELI)": "34.443.602/0001-35",
            "JUNGLE CHOCOLATE (NORTE PIONEIRO INDÚSTRIA E COMÉRCIO DE FUMOS EIRELI)": "34.443.602/0001-35",
            "JUNGLE VIRGÍNIA (NORTE PIONEIRO INDÚSTRIA E COMÉRCIO DE FUMOS EIRELI)": "34.443.602/0001-35",
            "MUCHACHOS TRADICIONAL (NORTE PIONEIRO INDÚSTRIA E COMÉRCIO DE FUMOS EIRELI)": "34.443.602/0001-35",
            "YERBA (ORC BRASIL COMÉRCIO DE TABACARIA LTDA)": "29.373.215/0001-30",
            "QUEBEC (ORION TOBACCO INDUSTRIA E COMERCIO LTDA)": "12.821.901/0001-23",
            "MONTEVIDEO (PALAZZO TABACUM LTDA)": "23.095.277/0001-40",
            "DRUM ORIGINAL (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "DP TABACOS (REGIONAL TABACOS LTDA)": "14.952.190/0001-51",
            "SASSO TABACCOS BRASIL (RMS TABACOS BRASIL LTDA)": "37.327.231/0001-14",
            "FUMO SUL (SAN MARTIN FABRICAÇÃO DE TABACO LTDA)": "15.006.574/0001-44",
            "SANTORINI PREMIUM (SANTORINI COMERCIO DE TABACOS LTDA)": "47.245.842/0001-77",
            "SELVA (SLV INDUSTRIA E COMERCIO LTDA)": "49.229.504/0001-77",
            "FUMO PARA CIGARROS TREVO TRADICIONAL (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "SASSO SESSION (STB SASSO TABACCOS BRASIL LTDA)": "37.327.231/0001-14",
            "VB TOBACO (STJA GRAN HABANO CHARUTARIA LTDA)": "26.652.153/0001-07",
            "MARAJÓ (SWISS SPIRIT INTERNATIONAL LTDA)": "18.750.908/0001-88",
            "FUMO PEÃO TRADICIONAL (TABACARIA GUANABARA LTDA EPP)": "78.402.013/0001-84",
            "TABACO DO VÉIO PIMENTA (TABACO DO VEIO PIMENTA LTDA)": "22.916.580/0001-02",
            "FINAMORE - GOLDEN VIRGINIA TOBACCO (TABACOS CISNE BRANCO FINAMORE LTDA – ME)": "12.389.368/0001-72",
            "FUMO DESFIADO CONQUISTADOR (TABACOS CONQUISTADOR LTDA)": "11.997.987/0001-87",
            "PUEBLO BLUE (TOBACCONIST COMERCIO DE TABACOS LTDA)": "06.863.253/0001-75",
            "PUEBLO CLASSIC (TOBACCONIST COMERCIO DE TABACOS LTDA)": "06.863.253/0001-75",
            "TOG (TOG BRASIL LTDA)": "50.485.254/0001-15",
            "MANDUPI (TONABE ARTIGOS DE HEADSHOP LTDA)": "49.593.350/0001-06",
            "TA NA MÃO (TONABE ARTIGOS DE HEADSHOP LTDA)": "49.593.350/0001-06",
            "ORIGINAL TABACO BRASIL (TRF INDUSTRIA TABACO LTDA)": "31.369.746/0001-09"
        },
        "🌾 Cigarro de Palha": {
            "PALHEIROS UNIVERSITHA TRADICIONAL (A L QUEIROZ INDUSTRIA DE PALHEIROS E SIMILARES LTDA)": "27.139.778/0001-32",
            "SANTROPEZ TRADICIONAL (BIFON & BIFON PALHEIROS E DERIVADOS DO TABACO LTDA)": "27.799.277/0001-82",
            "BROTHERS PAIOL (BROTHERS PAIOL FABRICA DE PRODUTOS ARTESANAIS LTDA)": "49.994.196/0001-76",
            "JC PALHEIROS (CLAUDIO DA SILVA DIAS)": "30.869.686/0001-12",
            "CRISTAL PALHEIRO (CRISTAL PALHEIROS FUMOS E COMÉRCIO DE PRODUTOS ARTESANAIS LTDA)": "33.626.845/0001-46",
            "PALHEIROS EMBAIXADOR TRADICIONAL (INDÚSTRIA E COMÉRCIO DE PALHEIROS EMBAIXADOR LTDA)": "40.730.684/0001-00",
            "PALHEIROS PAULISTINHA (INDUSTRIA E COMERCIO DE PALHEIROS PAULISTINHA)": "13.206.312/0001-06",
            "PALHEIROS PAULISTINHA MENTA (INDUSTRIA E COMERCIO DE PALHEIROS PAULISTINHA)": "13.206.312/0001-06",
            "PALHEIROS PAULISTINHA OURO (INDUSTRIA E COMERCIO DE PALHEIROS PAULISTINHA)": "13.206.312/0001-06",
            "PALHEIROS PAULISTINHA TRADICIONAL (INDUSTRIA E COMERCIO DE PALHEIROS PAULISTINHA)": "13.206.312/0001-06",
            "PALHEIRO JURITI SLIM (J2S TABACOS LTDA)": "52.083.832/0001-12",
            "PALHEIRO PANTANEIRO (J2S TABACOS LTDA)": "52.083.832/0001-12",
            "JA PALHEIRO (JA PALHEIROS LTDA)": "24.471.436/0001-27",
            "PF PALHEIROS DE FUMO (J.G CORREIA DA SILVA)": "44.060.506/0001-61",
            "JACK PAIOL’S ORIGINAL ULTRA PREMIUM (JOÃO RESENDE FILHO)": "28.528.287/0001-46",
            "PRADO PALHEIROS (JULIANA CAVATÃO)": "22.899.501/0001-94",
            "MANDELLE ORIGINAL BLEND (LR COMÉRCIO DE TABACOS LTDA)": "31.884.049/0001-88",
            "COYOTE (MINAS ARTEFATOS LTDA)": "27.072.327/0001-25",
            "COYOTE PALHEIROS PREMIUM (MINAS ARTEFATOS LTDA)": "27.072.327/0001-25",
            "PALHEIROS CANARINHO ORIGINAL (NEW INDUSTRIA E COMERCIO DE TABACOS LTDA)": "39.404.583/0001-51",
            "DIPALHA PALHEIROS (NORTE PIONEIRO INDÚSTRIA E COMÉRCIO DE FUMOS EIRELI)": "34.443.602/0001-35",
            "TIMBAL (NORTE PIONEIRO INDÚSTRIA E COMÉRCIO DE FUMOS EIRELI)": "34.443.602/0001-35",
            "TIMBAL MENTA (NORTE PIONEIRO INDÚSTRIA E COMÉRCIO DE FUMOS EIRELI)": "34.443.602/0001-35",
            "PIONEIRO EXTRA (NORTE PIONEIRO INDÚSTRIA E COMÉRCIO DE FUMOS EIRELI)": "34.443.602/0001-35",
            "PIONEIRO TRADICIONAL (NORTE PIONEIRO INDÚSTRIA E COMÉRCIO DE FUMOS EIRELI)": "34.443.602/0001-35",
            "PAERINHO (PAERINHO INDÚSTRIA E COMERCIO LTDA)": "04.857.318/0001-44",
            "PALHEIROS DOURADINHO OURO (PALHEIROS DOURADINHOS LTDA)": "26.084.455/0001-26",
            "PALHEIROS PIRACANJUBA (PALHEIROS PIRACANJUBA LTDA)": "25.057.001/0001-01",
            "PALHEIROS PIRACANJUBA OURO (PALHEIROS PIRACANJUBA LTDA)": "25.057.001/0001-01",
            "PALHEIROS TERRA TOMBADA TRADICIONAL (PALHEIROS TERRA TOMBADA LTDA)": "46.637.515/0001-06",
            "PORTO FARIA GOLD (PORTO FARIA LTDA - ME)": "03.221.399/0001-29",
            "PORTO FARIA PAULISTA (PORTO FARIA LTDA - ME)": "03.221.399/0001-29",
            "ROLO TABAK TRADICIONAL (ROLO TABAK COMERCIO E REPRESENTACAO LTDA)": "27.651.665/0001-11",
            "SOUZA PAIOL TRADICIONAL ORIGINAL (SOUZAPAIOL VASCONCELOS INDÚSTRIA E COMÉRCIO CIGARRO DE PALHA LTDA)": "32.956.729/0001-22",
            "PALHEIROS 3 LOBOS ORIGINAL (TL FABRICÃO DE PRODUTOS LTDA)": "34.099.121/0001-54",
            "YANKING (YANNKEE FÁBRICA DE CIGARROS DE PALHA LTDA)": "23.367.974/0001-03"
        },
        "🌬️ Fumo para Narguilé": {
            "NAY BLEND MANGA BANANA (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "NAY BLEND MANGO MELON (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "NAY BLEND PINEAPPLE GRAPE (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "NAY BLEND PINEAPPLE TWIST (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "NAY BUBBLE GRAPE (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "NAY CEREJA BLEND (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "NAY MARACUJA BLEND (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "NAY MELANCIA (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "NAY MINT (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "NAY RED BLEND FRAMBOESA & UVA (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "NAY SNOW (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "ZOMO MAX CHICLETE TUTTI FRUTTI (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "ZOMO MAX MAÇA VERDE (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "ZOMO MAX MELÃO (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "ZOMO MINT (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "ZOMO MIX BERRIES MINT (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "ZOMO PASSION LEMONADE (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "ZOMO STRONG MINT (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "ZOMO SWISS ALPS (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "ZOMO TWO APPLE BAHRAINI (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "ZOMO WATERMELON MINT (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "BABOS 66 (LATIN TOBACCO FLAVOURS INDUSTRIA E COMERCIO DE TABACO LTDA)": "37.449.144/0001-30",
            "CHACAL TOBACCO BUBBA MINT (NAPOLES INDUSTRIA E COMERCIO LTDA)": "39.668.077/0001-70",
            "CHACAL TOBACCO BUBBA WATERMELON (NAPOLES INDUSTRIA E COMERCIO LTDA)": "39.668.077/0001-70",
            "CHACAL TOBACCO GRAPE (NAPOLES INDUSTRIA E COMERCIO LTDA)": "39.668.077/0001-70",
            "CHACAL TOBACCO STRAWBERRY (NAPOLES INDUSTRIA E COMERCIO LTDA)": "39.668.077/0001-70",
            "SNS TOBACCO ABSOLUT MINT (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "SNS TOBACCO MORANGO E MELANCIA ICE (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL BANANA TROPICAL (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL BERRY (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL FRESH 66 (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL BURLEY MINT (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL CHERRY (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL CORN MAGIC (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL FRESH LEMON (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL FRESH MELON (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL FRUTTI (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL GRAPE (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL HAPOCALYX MINT (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL JABUTICABA TROPICAL (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL MANGA TROPICAL (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL MIX DUAS GOIABAS (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL MIX DUAS MAÇÃS VERDES (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL MIX FRUTAS ROXAS (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL MIX FRUTAS VERDES (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL MIX FRUTAS AMARELAS (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL MIX MORANGO E LARANJA (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL MORANGO TROPICAL (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL SORVETE DE LIMÃO (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL SORVETE DE PISTACHE (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL WATERMELON BOMB (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL YELLOW (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL YOGURT (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ADALYA ICE BON (PACTUAL COMÉRCIO E IMPORTAÇÃO LTDA)": "05.165.237/0001-46",
            "ADALYA 66 (PACTUAL COMÉRCIO E IMPORTAÇÃO LTDA)": "05.165.237/0001-46",
            "ADALYA SWISS (PACTUAL COMÉRCIO E IMPORTAÇÃO LTDA)": "05.165.237/0001-46",
            "ADALYA TWO MELON ICE (PACTUAL COMÉRCIO E IMPORTAÇÃO LTDA)": "05.165.237/0001-46",
            "ONA TOBACCO 66 (TURBRAS IMPORTACAO E EXPORTACAO LTD)": "51.094.844/0001-80",
            "ONA TOBACCO CALLISTA (TURBRAS IMPORTACAO E EXPORTACAO LTD)": "51.094.844/0001-80",
            "ONA TOBACCO COLA (TURBRAS IMPORTACAO E EXPORTACAO LTD)": "51.094.844/0001-80",
            "ONA TOBACCO DOMINIC (TURBRAS IMPORTACAO E EXPORTACAO LTD)": "51.094.844/0001-80",
            "ONA TOBACCO LEMON MINT (TURBRAS IMPORTACAO E EXPORTACAO LTD)": "51.094.844/0001-80",
            "ONA TOBACCO TWO APPLES (TURBRAS IMPORTACAO E EXPORTACAO LTD)": "51.094.844/0001-80"
        },
        "🪈 Fumo para Cachimbo": {
            "IRLANDEZ TRADICIONAL ORIGINAL (TABACOS CISNE BRANCO FINAMORE LTDA – ME)": "12.389.368/0001-72"
        }
    }
}

# ==========================================
# INTEGRAÇÃO INTELIGENTE
# ==========================================
def obter_banco_atualizado():
    banco_dinamico = copy.deepcopy(DB_PRODUTOS_BASE)
    if supabase_client:
        try:
            resp = supabase_client.table('produtos_customizados').select('*').execute()
            for row in resp.data:
                cat, tipo, prod, cnpj, status = row['categoria'], row['tipo'], row['produto'], row['cnpj'], row['status']
                if cat in banco_dinamico:
                    if tipo not in banco_dinamico[cat]: banco_dinamico[cat][tipo] = {}
                    val_final = cnpj if "Ilegal" not in status else f"{cnpj} [Ilegal]"
                    banco_dinamico[cat][tipo][prod] = val_final
        except Exception: pass
    return banco_dinamico

def salvar_produto_nuvem(categoria, tipo, produto, cnpj, status):
    if supabase_client:
        try:
            resp = supabase_client.table('produtos_customizados').select('*').eq('produto', produto).execute()
            if not resp.data:
                supabase_client.table('produtos_customizados').insert({
                    "categoria": categoria, "tipo": tipo, "produto": produto, "cnpj": cnpj, "status": status
                }).execute()
                registrar_log("Novo Produto Cadastrado", f"A marca '{produto}' foi salva para futuras fiscalizações.")
        except Exception: pass

DB_PRODUTOS = obter_banco_atualizado()

def get_cnpj_mapping():
    mapping = {}
    for cat, tipos in DB_PRODUTOS.items():
        for tipo, produtos in tipos.items():
            for prod, cnpj in produtos.items():
                cnpj_limpo = re.sub(r'\D', '', cnpj) 
                if len(cnpj_limpo) > 10: mapping[cnpj_limpo] = prod
    return mapping
CNPJ_TO_PRODUTO = get_cnpj_mapping()

# ==========================================
# RDC E PDF CORE 
# ==========================================
def clean_text_for_pdf(text):
    if not text: return text
    return text.encode('latin-1', 'ignore').decode('latin-1')

def ler_cnpj_imagem(imagem_bytes):
    if not HAS_OCR: return None
    try:
        img = Image.open(io.BytesIO(imagem_bytes))
        texto = pytesseract.image_to_string(img)
        numeros = re.sub(r'\D', '', texto)
        for cnpj_banco in CNPJ_TO_PRODUTO.keys():
            if cnpj_banco in numeros: return cnpj_banco
        return None
    except Exception: return None

def obter_fundamentacao_legal(categoria, status):
    fundamentos = []
    if "DEF" in categoria: 
        fundamentos.append("RDC nº 855/2024 e Lei 6.437/77 (Comercialização de DEF)")
    else:
        if "Propaganda" in categoria or "Propaganda" in status: 
            fundamentos.append("RDC nº 840/2023 e Lei 9.294/96 (Propaganda Irregular)")
        if "Ilegal" in status or "Apreensão" in categoria or "Nao Registrado" in status: 
            fundamentos.append("RDC nº 896/2024 e Lei 6.437/77 (Produto Sem Registro)")
    if not fundamentos: fundamentos.append("Amostragem / RDC nº 838/2023 (Fiscalização de Embalagem)")
    return " | ".join(fundamentos)

def gerar_excel(fisc):
    flat_data = []
    for loja in fisc['lojas']:
        for item in loja['itens']:
            flat_item = item.copy()
            flat_item['Loja'] = f"Loja {loja['numero']} - {loja['nome']}"
            flat_data.append(flat_item)
    df = pd.DataFrame(flat_data)
    if not df.empty: df = df.drop(columns=['Foto 1 Bytes', 'Foto 2 Bytes'], errors='ignore')
    out = io.BytesIO()
    with pd.ExcelWriter(out, engine='openpyxl') as w:
        if df.empty: df.to_excel(w, index=False, sheet_name='Sem_Apreensoes')
        else:
            for lname in df['Loja'].unique():
                aba = ''.join(c for c in clean_text_for_pdf(lname) if c.isalnum() or c.isspace() or c == '-').strip()[:31] or "Loja"
                df[df['Loja'] == lname].to_excel(w, index=False, sheet_name=aba)
    return out.getvalue()

def gerar_pdf(fisc):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("helvetica", style="B", size=15)
    pdf.cell(0, 10, clean_text_for_pdf("Auto de Inspecao e Apreensao - GGTAB/ANVISA"), ln=True, align='C')
    pdf.set_font("helvetica", size=9)
    pdf.cell(0, 8, clean_text_for_pdf(f"Operacao: {fisc.get('operacao_id', 'Local')} | Fiscal: {st.session_state['nome_fiscal']}"), ln=True, align='C')
    pdf.line(10, 28, 200, 28)
    pdf.ln(8)
    
    if not fisc['lojas']: pdf.cell(0, 10, "Nenhuma loja fiscalizada nesta operacao.", ln=True)
    else:
        for loja in fisc['lojas']:
            pdf.set_font("helvetica", style="B", size=13)
            pdf.set_text_color(0, 51, 102)
            pdf.cell(0, 10, clean_text_for_pdf(f"Estabelecimento: Loja {loja['numero']} - {loja['nome']}"), ln=True)
            pdf.set_text_color(0, 0, 0)
            if not loja['itens']:
                pdf.set_font("helvetica", style="I", size=10)
                pdf.cell(0, 6, "Nenhum item apreendido.", ln=True)
                pdf.ln(4)
                continue
            for item in loja['itens']:
                pdf.set_font("helvetica", style="B", size=11)
                pdf.cell(0, 7, clean_text_for_pdf(f"Item: {item['Produto']} (Hora: {item['Hora']})"), ln=True)
                pdf.set_font("helvetica", size=10)
                pdf.cell(0, 6, clean_text_for_pdf(f"Categoria: {item['Categoria']} | Tipo: {item['Tipo']}"), ln=True)
                
                qtd_str = f"Qtd: {item['Quantidade']} und. | Status: {item['Status']}"
                if "Propaganda" in item['Categoria'] or "Propaganda" in item['Status']: 
                    qtd_str = f"Peças Publicitárias / Qtd: {item['Quantidade']} | Status: {item['Status']}"
                    
                pdf.cell(0, 6, clean_text_for_pdf(qtd_str), ln=True)
                pdf.set_font("helvetica", style="B", size=10)
                pdf.cell(0, 6, clean_text_for_pdf(f"CNPJ / Lote: {item['CNPJ Identificado'].replace(' [Ilegal]', '')}"), ln=True)
                
                fund = obter_fundamentacao_legal(item['Categoria'], item['Status'])
                pdf.set_font("helvetica", style="I", size=9)
                pdf.set_text_color(200, 0, 0) if ("Ilegal" in item['Status'] or "Propaganda" in item['Status']) else pdf.set_text_color(0, 100, 0)
                pdf.cell(0, 6, clean_text_for_pdf(f"Fundamentação Legal: {fund}"), ln=True)
                pdf.set_text_color(0, 0, 0) 
                
                foto1, foto2 = item.get('Foto 1 Bytes'), item.get('Foto 2 Bytes')
                if foto1 or foto2:
                    pdf.ln(2)
                    if pdf.get_y() > 230: pdf.add_page()
                    x_offset = 10
                    if foto1: pdf.image(io.BytesIO(foto1), x=x_offset, y=pdf.get_y(), w=50); x_offset += 60 
                    if foto2: pdf.image(io.BytesIO(foto2), x=x_offset, y=pdf.get_y(), w=50)
                pdf.ln(55) 
                pdf.line(10, pdf.get_y(), 200, pdf.get_y())
                pdf.ln(4)
    return bytes(pdf.output())

# ==========================================
# INICIALIZAÇÃO E SESSÃO
# ==========================================
if 'tentativas_login' not in st.session_state: st.session_state['tentativas_login'] = 0
if 'autenticado' not in st.session_state: st.session_state['autenticado'] = False 
if 'nome_fiscal' not in st.session_state: st.session_state['nome_fiscal'] = ""
if 'historico_operacoes' not in st.session_state: st.session_state['historico_operacoes'] = []
if 'fisc_ativa' not in st.session_state: st.session_state['fisc_ativa'] = None
if 'loja_ativa' not in st.session_state: st.session_state['loja_ativa'] = None
if 'chat_ia' not in st.session_state: 
    st.session_state['chat_ia'] = [{"role": "assistant", "content": "Olá, Fiscal. Sou a IA Jurídica da GGTAB. Pergunte-me sobre Cigarros Eletrônicos, Propaganda, Embalagens ou Apreensões de produtos sem registro."}]

def tela_login():
    st.title("🛡️ Portal de Fiscalização GGTAB")
    st.markdown("---")
    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        with st.form("form_login"):
            st.subheader("Acesso ao Servidor Único")
            usuario = st.text_input("Login")
            senha = st.text_input("Senha", type="password")
            nome = st.text_input("Seu Nome Completo")
            if st.form_submit_button("Entrar no Sistema", type="primary"):
                if usuario == "GGTAB" and senha == "CCTAB" and nome.strip() != "":
                    st.session_state['autenticado'], st.session_state['nome_fiscal'] = True, nome.strip()
                    registrar_log("Login", "Acesso concedido ao sistema.")
                    st.rerun()
                else:
                    st.toast("❌ Credenciais inválidas.", icon="❌")

# ==========================================
# INTERFACE PRINCIPAL (MODAIS, BI, IA RAG)
# ==========================================
def app():
    global DB_PRODUTOS 
    DB_PRODUTOS = obter_banco_atualizado()

    # --- MODAIS ---
    @st.dialog("📍 Registrar Novo Estabelecimento")
    def modal_nova_loja():
        n_loja = st.number_input("Nº da Loja", min_value=1)
        nome_loja = st.text_input("Endereço ou Nome Fantasia")
        if st.button("Iniciar Auditoria", type="primary", use_container_width=True):
            if nome_loja.strip():
                st.session_state['loja_ativa'] = {"numero": n_loja, "nome": nome_loja, "itens": []}
                st.toast(f"✅ Auditoria iniciada: Loja {n_loja}", icon="✅")
                st.rerun()
            else:
                st.toast("⚠️ Preencha o nome do estabelecimento.", icon="⚠️")

    @st.dialog("➕ Cadastrar Nova Marca no Banco Global")
    def modal_cadastro():
        cat_cad = st.selectbox("Categoria Macro", ["Selecione...", "💨 DEF (Dispositivos Eletrônicos para Fumar)", "🍂 Tabacos e Derivados (Registrados pela ANVISA) - Propaganda Irregular", "🍂 Tabacos e Derivados (Irregulares/Ilegais) - Apreensão", "🍂 Tabacos e Derivados (Irregulares/Ilegais) - Apreensão e Propaganda"])
        
        tipo_cad = "Aguardando Categoria..."
        if cat_cad != "Selecione...":
            chave_db_cad = "💨 DEF (Dispositivos Eletrônicos para Fumar)" if "DEF" in cat_cad else "🍂 TABACOS E DERIVADOS"
            tipos_existentes = list(DB_PRODUTOS[chave_db_cad].keys()) + ["+ Criar Novo Tipo"]
            tipo_cad = st.selectbox("Tipo de Produto", ["Selecione..."] + tipos_existentes)
            if tipo_cad == "+ Criar Novo Tipo": tipo_cad = st.text_input("Nome do Novo Tipo")
        else:
            st.selectbox("Tipo de Produto", [tipo_cad])

        prod_cad = st.text_input("Nome Comercial da Marca")
        cnpj_cad = st.text_input("CNPJ (Se houver)")
        
        status_cad = "Regular" if "Registrados" in cat_cad else "Ilegal/Apreensão"
        if cat_cad != "Selecione...":
            st.caption(f"Status automático: {'✅ Regular' if status_cad == 'Regular' else '❌ Ilegal'}")
        
        if st.button("Salvar no Banco Global", type="primary", use_container_width=True):
            if cat_cad != "Selecione..." and tipo_cad != "Aguardando Categoria..." and prod_cad and tipo_cad:
                salvar_produto_nuvem(chave_db_cad, tipo_cad, prod_cad, cnpj_cad if cnpj_cad else "Sem CNPJ", status_cad)
                st.toast(f"✅ A marca '{prod_cad}' foi adicionada à Nuvem!", icon="✅")
                st.rerun()
            else: st.toast("⚠️ Preencha todos os campos.", icon="⚠️")

    @st.dialog("📦 Adicionar Nova Infração / Apreensão")
    def modal_infracao():
        cat_macro = st.selectbox("Categoria Macro da Infração", ["Selecione...", "💨 DEF (Dispositivos Eletrônicos para Fumar)", "🍂 Tabacos e Derivados (Registrados pela ANVISA) - Propaganda Irregular", "🍂 Tabacos e Derivados (Irregulares/Ilegais) - Apreensão", "🍂 Tabacos e Derivados (Irregulares/Ilegais) - Apreensão e Propaganda"])
                
        if cat_macro != "Selecione...":
            is_def = "DEF" in cat_macro
            is_propaganda = "Propaganda" in cat_macro and "Apreensão e Propaganda" not in cat_macro
            is_ilegal = "Irregulares" in cat_macro
            is_ambos = "Apreensão e Propaganda" in cat_macro
            chave_db = "💨 DEF (Dispositivos Eletrônicos para Fumar)" if is_def else "🍂 TABACOS E DERIVADOS"
            
            tipos = ["Selecione..."] + list(DB_PRODUTOS[chave_db].keys())
            if is_ilegal or is_def or is_ambos: tipos.append("⚠️ OUTRO TIPO / MARCA NOVA")
            tipo_prod = st.selectbox("Tipo de Produto", tipos)
            
            if tipo_prod != "Selecione...":
                is_novo_tipo = "⚠️" in tipo_prod
                if is_novo_tipo: prod = "⚠️ CADASTRAR NOVA MARCA ILEGAL"
                else:
                    todos_prods_tipo = DB_PRODUTOS[chave_db][tipo_prod]
                    if is_propaganda: prods_filtrados = [p for p, v in todos_prods_tipo.items() if "Ilegal" not in v]
                    elif is_ilegal or is_ambos: prods_filtrados = [p for p, v in todos_prods_tipo.items() if "Ilegal" in v]
                    else: prods_filtrados = list(todos_prods_tipo.keys())
                        
                    prods_opcoes = ["Selecione..."] + prods_filtrados
                    if is_ilegal or is_def or is_ambos: prods_opcoes.append("⚠️ CADASTRAR NOVA MARCA ILEGAL")
                    prod = st.selectbox("Busque o Produto" if is_propaganda else "Selecione a Marca", prods_opcoes)
                
                if prod != "Selecione...":
                    qtd = st.number_input("Quantidade (Unidades/Peças)", min_value=1)
                    
                    st.markdown("**Captura de Evidências**")
                    f1 = st.camera_input("1 - Embalagem Frontal / Propaganda")
                    f2 = st.camera_input("2 - Lote / CNPJ / Detalhes")
                    f1_bytes = f1.getvalue() if f1 else None
                    f2_bytes = f2.getvalue() if f2 else None

                    cnpj_extraido = ""
                    if f2 and HAS_OCR and st.button("🤖 Tentar Auto-Preencher CNPJ", type="secondary"):
                        cnpj_lido = ler_cnpj_imagem(f2_bytes)
                        if cnpj_lido:
                            st.toast("🤖 CNPJ Lido com sucesso!", icon="🤖")
                            cnpj_extraido = cnpj_lido
                        else: st.toast("⚠️ Nenhum CNPJ nítido.", icon="⚠️")

                    if prod == "⚠️ CADASTRAR NOVA MARCA ILEGAL":
                        n_novo = st.text_input("Nome da Nova Marca Ilegal")
                        c_novo = st.text_input("CNPJ Falso (Opcional)", value=cnpj_extraido)
                        t_novo = st.text_input("Tipo Específico", value=tipo_prod if not is_novo_tipo else "")
                        
                        if st.button("➕ Confirmar Inserção", type="primary", use_container_width=True):
                            nome_final = n_novo if n_novo else "Produto S/ Nome"
                            cnpj_final = c_novo if c_novo else "Sem CNPJ"
                            tipo_final = t_novo if t_novo else "Outros"
                            status_final = "Ilegal/Apreensão e Propaganda" if is_ambos else "Ilegal/Apreensão"
                            
                            salvar_produto_nuvem(chave_db, tipo_final, nome_final, cnpj_final, "Ilegal/Apreensão")
                            cat_limpa = "Tabaco Irregular (Sem Registro + Propaganda)" if is_ambos else ("Tabaco Irregular (Sem Registro)" if is_ilegal else "DEF")
                            
                            st.session_state['loja_ativa']['itens'].append({
                                "Categoria": cat_limpa, "Tipo": tipo_final.replace("🚬 ", "").replace("🕴️ ", "").replace("🌿 ", "").replace("🌾 ", "").replace("🌬️ ", "").replace("🪈 ", ""), 
                                "Produto": nome_final, "Status": status_final, "CNPJ Identificado": cnpj_final, 
                                "Quantidade": qtd, "Hora": datetime.now().strftime('%H:%M:%S'),
                                "Foto 1 Bytes": f1_bytes, "Foto 2 Bytes": f2_bytes
                            })
                            st.toast("✅ Infração Registrada!", icon="✅")
                            st.rerun()
                    else:
                        if st.button("➕ Confirmar Infração", type="primary", use_container_width=True):
                            cnpj_banco = DB_PRODUTOS[chave_db][tipo_prod][prod]
                            if is_propaganda: status_banco, cat_limpa = "Autuação (Propaganda Irregular)", "Propaganda Irregular (Produto Registrado)"
                            elif is_ambos: status_banco, cat_limpa = "Ilegal/Apreensão e Propaganda", "Tabaco Irregular (Sem Registro + Propaganda)"
                            elif is_ilegal: status_banco, cat_limpa = "Ilegal/Apreensão", "Tabaco Irregular (Sem Registro)"
                            else: status_banco, cat_limpa = "Ilegal/Apreensão", "DEF"
                            
                            st.session_state['loja_ativa']['itens'].append({
                                "Categoria": cat_limpa, "Tipo": tipo_prod.replace("🚬 ", "").replace("🕴️ ", "").replace("🌿 ", "").replace("🌾 ", "").replace("🌬️ ", "").replace("🪈 ", ""), 
                                "Produto": prod, "Status": status_banco, "CNPJ Identificado": cnpj_banco.replace(" [Ilegal]", ""), 
                                "Quantidade": qtd, "Hora": datetime.now().strftime('%H:%M:%S'),
                                "Foto 1 Bytes": f1_bytes, "Foto 2 Bytes": f2_bytes
                            })
                            st.toast("✅ Infração Registrada!", icon="✅")
                            st.rerun()

    # --- MENU LATERAL ---
    with st.sidebar:
        st.markdown(f"**Fiscal Ativo:** 👮 {st.session_state['nome_fiscal']}")
        st.markdown("---")
        menu = option_menu(
            menu_title="Painel GGTAB",
            options=["Dashboard Geral", "Consulta e Cadastro", "Nova Fiscalização", "Histórico / Edição", "Assistente Jurídico (IA)", "Monitoramento (Logs)"],
            icons=["bar-chart-fill", "search", "clipboard-check-fill", "folder-fill", "robot", "eye-fill"],
            menu_icon="bank",
            default_index=0,
            styles={
                "container": {"padding": "0!important", "background-color": "transparent", "border": "none"},
                "icon": {"color": "#00A859", "font-size": "16px"}, 
                "nav-link": {"font-size": "14px", "text-align": "left", "margin":"2px"},
                "nav-link-selected": {"background-color": "#0A3B7C", "color": "white", "font-weight": "bold"},
            }
        )
        
        if st.session_state['fisc_ativa']:
            duracao = datetime.now() - st.session_state['fisc_ativa']['data_inicio']
            st.metric(label="⏱️ Operação Ativa", value=f"{duracao.seconds//3600:02d}:{(duracao.seconds//60)%60:02d}:{duracao.seconds%60:02d}")
        
        st.markdown("---")
        if supabase_client: st.success("🟢 Nuvem Ativa")
        else: st.error("🔴 Sem Nuvem")
        
        if st.button("Sair do Sistema", use_container_width=True):
            registrar_log("Logout", "Utilizador saiu do sistema.")
            st.session_state['autenticado'] = False
            st.rerun()

    # --- TELA 1: DASHBOARD ENTERPRISE (BI FORA DO BI) ---
    if menu == "Dashboard Geral":
        st.title("📈 Painel Executivo de Inteligência GGTAB")
        st.markdown("Visão global consolidada. O sistema cruza os dados locais em andamento com a base nacional da Nuvem.")
        
        dados_bi = []
        if supabase_client:
            try:
                resp = supabase_client.table("apreensoes").select("*").execute()
                dados_bi.extend(resp.data)
            except Exception: pass
            
        for op in st.session_state['historico_operacoes'] + ([st.session_state['fisc_ativa']] if st.session_state['fisc_ativa'] else []):
            for loja in op['lojas']:
                for it in loja['itens']:
                    dados_bi.append({
                        "operacao_id": op['operacao_id'], "loja": loja['nome'],
                        "categoria": it['Categoria'], "tipo": it['Tipo'],
                        "produto": it['Produto'], "status": it['Status'],
                        "quantidade": it['Quantidade']
                    })

        df_bi = pd.DataFrame(dados_bi)

        if not df_bi.empty:
            total_ops = df_bi['operacao_id'].nunique()
            total_lojas = df_bi['loja'].nunique()
            total_produtos = df_bi['quantidade'].sum()
            
            df_ilegais = df_bi[df_bi['status'].str.contains("Ilegal|Propaganda", case=False, na=False)]
            total_ilegais = df_ilegais['quantidade'].sum() if not df_ilegais.empty else 0

            c1, c2, c3, c4 = st.columns(4)
            c1.metric("Total de Operações (Histórico)", total_ops)
            c2.metric("Lojas Fiscalizadas", total_lojas)
            c3.metric("Volume de Itens/Peças", f"{total_produtos:,}")
            c4.metric("Total de Infrações (Ilegal/Propaganda)", f"{total_ilegais:,}", delta="Alerta Vermelho", delta_color="inverse")
            st.markdown("---")

            if HAS_PLOTLY:
                col_graf1, col_graf2 = st.columns([1, 1.2])
                with col_graf1:
                    st.subheader("Distribuição Regulatória")
                    df_status = df_bi.copy()
                    df_status['Status Geral'] = df_status['status'].apply(lambda x: "Regular" if x == "Regular" else "Infração (Ilegal/Propaganda)")
                    df_pie = df_status.groupby("Status Geral")['quantidade'].sum().reset_index()
                    fig1 = px.pie(df_pie, values='quantidade', names='Status Geral', hole=0.4,
                                  color='Status Geral', color_discrete_map={"Regular": "#00A859", "Infração (Ilegal/Propaganda)": "#D93838"})
                    fig1.update_layout(margin=dict(t=30, b=0, l=0, r=0))
                    st.plotly_chart(fig1, use_container_width=True)

                with col_graf2:
                    st.subheader("Top 5 Produtos Autuados")
                    df_top = df_ilegais.groupby("produto")['quantidade'].sum().reset_index()
                    df_top = df_top.sort_values(by="quantidade", ascending=False).head(5)
                    
                    if not df_top.empty:
                        fig2 = px.bar(df_top, x="quantidade", y="produto", orientation='h', text='quantidade',
                                      color_discrete_sequence=["#0A3B7C"])
                        fig2.update_layout(yaxis={'categoryorder':'total ascending'}, margin=dict(t=30, b=0, l=0, r=0))
                        st.plotly_chart(fig2, use_container_width=True)
                    else: st.info("Nenhuma infração registrada para gerar o ranking de produtos.")
                        
                st.markdown("---")
                st.subheader("Mapeamento de Infrações por Tipo (DEF vs Derivados)")
                df_tipo = df_ilegais.groupby("tipo")['quantidade'].sum().reset_index()
                if not df_tipo.empty:
                    fig3 = px.bar(df_tipo, x="tipo", y="quantidade", color="tipo", text="quantidade", color_discrete_sequence=px.colors.qualitative.Bold)
                    fig3.update_layout(margin=dict(t=30, b=0, l=0, r=0), showlegend=False)
                    st.plotly_chart(fig3, use_container_width=True)
        else: st.info("Nenhuma operação registrada na Nuvem ou na sessão atual. Inicie uma nova auditoria para popular o Dashboard.")

    # --- TELA 2: ASSISTENTE JURÍDICO (RAG / IA) ---
    elif menu == "Assistente Jurídico (IA)":
        st.title("⚖️ Assistente Jurídico GGTAB (IA Avançada)")
        st.markdown("Consulte a legislação da ANVISA. Se você tiver a Chave da API, a IA interpretará textos complexos livremente. Caso contrário, operará no modo reativo padrão.")
        
        for msg in st.session_state['chat_ia']:
            with st.chat_message(msg["role"]): st.markdown(msg["content"])

        prompt = st.chat_input("Ex: 'Qual a punição para venda de pods?'")
        if prompt:
            st.session_state['chat_ia'].append({"role": "user", "content": prompt})
            with st.chat_message("user"): st.markdown(prompt)
            
            # O "CÉREBRO INTELIGENTE" - Tenta a IA do Google primeiro, se falhar, usa o Motor Interno Seguro.
            resposta_ia = ""
            if HAS_GEMINI and "GEMINI_API_KEY" in st.secrets:
                try:
                    genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
                    instrucao = "Você é um Procurador Jurídico Especialista da GGTAB (ANVISA). Ajude os fiscais em campo com a legislação sanitária. Use a RDC 855/2024 (que proíbe Dispositivos Eletrônicos para Fumar - DEF), RDC 840/2023 (Propaganda irregular), RDC 896/2024 (Registro de produtos) e Lei 6.437/77. Responda de forma direta e profissional baseando-se nestas normativas."
                    
                    historico_gemini = []
                    for m in st.session_state['chat_ia'][1:-1]:
                        historico_gemini.append({"role": "model" if m["role"] == "assistant" else "user", "parts": [m["content"]]})
                        
                    model = genai.GenerativeModel('gemini-3.6-flash', system_instruction=instrucao)
                    chat = model.start_chat(history=historico_gemini)
                    response = chat.send_message(prompt)
                    resposta_ia = response.text

                except Exception as e:
                    erro_str = str(e)
                    if "429" in erro_str:
                        resposta_ia = "⏳ **Controle de Tráfego:** O limite de consultas por minuto da cota gratuita foi atingido (Proteção Anti-Spam do Google). Por favor, aguarde cerca de 20 segundos e envie a sua pergunta novamente."
                    else:
                        resposta_ia = f"⚠️ Ocorreu um erro de ligação com a IA Externa: **{erro_str}** \n\nAcionando o Motor Interno restrito...\n\n"
                    
            if not resposta_ia or ("⚠️" in resposta_ia and "429" not in resposta_ia):
                base_conhecimento = {
                    "eletronico|def|vape|pod": "**RDC nº 855/2024**: Proíbe a fabricação, a importação, a comercialização, a distribuição, o armazenamento, o transporte e a propaganda de dispositivos eletrônicos para fumar (DEF).\n\n*Ação Sugerida:* O produto carece de registro na Anvisa, sendo passível de apreensão sumária e inutilização, com base também na Lei 6.437/77.",
                    "propaganda|anuncio|cartaz|display": "**RDC nº 840/2023 & Lei 9.294/96**: É terminantemente proibida a propaganda comercial de produtos fumígenos derivados ou não do tabaco. Expositores não podem conter iluminação que destaque o produto, nem cartazes promocionais.\n\n*Ação Sugerida:* Autuação do estabelecimento por exibição irregular, mesmo que o produto seja registrado.",
                    "registro|ilegal|sem cnpj": "**RDC nº 896/2024**: Dispõe sobre o registro de produtos fumígenos derivados do tabaco. Produtos sem registro válido na Anvisa não podem ser comercializados.\n\n*Ação Sugerida:* Apreensão cautelar dos itens sem registro, fundamentada na Lei 6.437/77 por exposição à venda de produto irregular.",
                    "embalagem|advertencia": "**RDC nº 838/2023**: Exige a presença obrigatória de advertências sanitárias e imagens padronizadas pela Anvisa nas embalagens de produtos fumígenos.\n\n*Ação Sugerida:* Fiscalização de embalagem; produto em desacordo está sujeito a recolhimento."
                }
                resposta_interna = "Não encontrei uma fundamentação exata no motor interno restrito. Tente buscar por termos diretos: **DEF, Propaganda, Registro ou Embalagem**."
                prompt_limpo = prompt.lower()
                for chave, texto in base_conhecimento.items():
                    if any(p in prompt_limpo for p in chave.split("|")):
                        resposta_interna = texto
                        break
                resposta_ia += resposta_interna
                
            st.session_state['chat_ia'].append({"role": "assistant", "content": resposta_ia})
            with st.chat_message("assistant"): st.markdown(resposta_ia)

    # --- TELA 3: CONSULTA E CADASTRO ---
    elif menu == "Consulta e Cadastro":
        st.title("🗃️ Gestão de Produtos")
        st.markdown("Explore a base completa. Clique no botão abaixo para adicionar permanentemente uma nova marca Ilegal ou Regular na nuvem.")
        if st.button("➕ Cadastrar Nova Marca na Nuvem", type="primary"): modal_cadastro()
            
        resultados = []
        for cat, tipos in DB_PRODUTOS.items():
            for tipo, produtos in tipos.items():
                for prod, cnpj in produtos.items():
                    status_base = "✅ Regular" if "Ilegal" not in cnpj else "❌ Ilegal (Apreensão)"
                    resultados.append({"Categoria": cat, "Tipo": tipo, "Produto": prod, "CNPJ": cnpj.replace(" [Ilegal]", ""), "Status": status_base})
        
        df_resultados = pd.DataFrame(resultados)
        if HAS_AGGRID:
            gb = GridOptionsBuilder.from_dataframe(df_resultados)
            gb.configure_pagination(paginationAutoPageSize=True, paginationPageSize=15)
            gb.configure_default_column(filter=True, sortable=True, resizable=True)
            AgGrid(df_resultados, gridOptions=gb.build(), theme='streamlit', fit_columns_on_grid_load=True)
        else: st.dataframe(df_resultados, use_container_width=True)

    # --- TELA 4: NOVA FISCALIZAÇÃO ---
    elif menu == "Nova Fiscalização":
        st.title("📝 Registro de Operação")
        if not st.session_state['fisc_ativa']:
            if st.button("▶️ Iniciar Nova Operação de Fiscalização", type="primary"):
                op_id = f"OP-{len(st.session_state['historico_operacoes']) + 1}-{datetime.now().strftime('%Y%m%d%H%M')}"
                st.session_state['fisc_ativa'] = {"id": op_id, "operacao_id": op_id, "data_inicio": datetime.now(), "lojas": []}
                registrar_log("Operação Iniciada", f"Criou a {op_id}")
                st.rerun()
            return
            
        st.caption(f"Operação Ativa: {st.session_state['fisc_ativa']['operacao_id']}")
        
        if not st.session_state['loja_ativa']:
            st.info("Nenhuma loja ativa no momento. Inicie uma nova auditoria para registrar apreensões.")
            c1, c2 = st.columns([1, 3])
            if c1.button("📍 Entrar em Novo Estabelecimento", type="primary"): modal_nova_loja()
            
            if st.session_state['fisc_ativa']['lojas']:
                if c2.button("🏁 Finalizar Operação Total (Sincronizar Nuvem)", type="secondary"):
                    fisc_atual = st.session_state['fisc_ativa']
                    if supabase_client:
                        dados = []
                        for loja in fisc_atual['lojas']:
                            for it in loja['itens']:
                                dados.append({
                                    "operacao_id": fisc_atual['operacao_id'], "data_hora": datetime.now().isoformat(),
                                    "fiscal": st.session_state['nome_fiscal'], "loja": f"Loja {loja['numero']} - {loja['nome']}",
                                    "categoria": it['Categoria'], "tipo": it['Tipo'], "produto": it['Produto'], 
                                    "status": it['Status'], "cnpj": it['CNPJ Identificado'].replace(" [Ilegal]", ""), "quantidade": it['Quantidade']
                                })
                        if dados: supabase_client.table("apreensoes").insert(dados).execute()
                        registrar_log("Operação Finalizada", f"Salvou {len(dados)} infrações.")
                    st.session_state['historico_operacoes'].append(fisc_atual)
                    st.session_state['fisc_ativa'] = None
                    st.toast("✅ Operação finalizada e enviada para a Nuvem!", icon="✅")
                    st.rerun()
            return

        loja = st.session_state['loja_ativa']
        st.subheader(f"🏬 Loja {loja['numero']} - {loja['nome']}")
        c1, c2 = st.columns([2, 1])
        if c1.button("➕ Registrar Nova Infração", type="primary", use_container_width=True): modal_infracao()
        if c2.button("🔒 Encerrar Auditoria nesta Loja", type="secondary", use_container_width=True):
            registrar_log("Loja Concluída", f"Fechou a Loja {loja['numero']}")
            st.session_state['fisc_ativa']['lojas'].append(st.session_state['loja_ativa'])
            st.session_state['loja_ativa'] = None
            st.rerun()
            
        if loja['itens']:
            st.markdown("### Infrações Registradas")
            df_loja = pd.DataFrame(loja['itens']).drop(columns=['Foto 1 Bytes', 'Foto 2 Bytes'], errors='ignore')
            st.dataframe(df_loja, use_container_width=True)
        else: st.info("Nenhuma infração registrada nesta loja até o momento.")

    # --- TELA 5: HISTÓRICO / EDIÇÃO ---
    elif menu == "Histórico / Edição":
        st.title("📂 Histórico e Edição")
        ops = st.session_state['historico_operacoes']
        if not ops: st.info("Nenhuma operação concluída na sessão.")
        else:
            op_dict = {f"{op['operacao_id']}": i for i, op in enumerate(ops)}
            escolha = st.selectbox("Selecione a Operação:", list(op_dict.keys()))
            idx = op_dict[escolha]
            fisc_edit = ops[idx]
            
            c_rel, c_edit, c_del = st.columns([2, 2, 2])
            c_rel.download_button("📊 Baixar Excel", data=gerar_excel(fisc_edit), file_name=f"{fisc_edit['operacao_id']}.xlsx", use_container_width=True)
            c_edit.download_button("📄 Baixar PDF", data=gerar_pdf(fisc_edit), file_name=f"{fisc_edit['operacao_id']}.pdf", type="primary", use_container_width=True)
            if c_del.button("🗑️ Excluir Operação", use_container_width=True):
                if supabase_client:
                    try: supabase_client.table("apreensoes").delete().eq("operacao_id", fisc_edit['operacao_id']).execute()
                    except Exception: pass
                st.session_state['historico_operacoes'].pop(idx)
                st.toast("✅ Operação excluída.", icon="✅")
                st.rerun()
            
            for l_idx, loja in enumerate(fisc_edit['lojas']):
                with st.expander(f"🏬 Loja {loja['numero']} - {loja['nome']}", expanded=True):
                    for i_idx, item in enumerate(loja['itens']):
                        c1, c2, c3, c4 = st.columns([3, 1, 2, 1])
                        item['Produto'] = c1.text_input(f"Produto #{i_idx+1}", value=item['Produto'], key=f"p_{idx}_{l_idx}_{i_idx}")
                        item['Quantidade'] = c2.number_input(f"Qtd", value=item['Quantidade'], key=f"q_{idx}_{l_idx}_{i_idx}")
                        item['Status'] = c3.text_input(f"Status", value=item['Status'], key=f"s_{idx}_{l_idx}_{i_idx}")
                        if c4.button("❌ Del", key=f"d_{idx}_{l_idx}_{i_idx}"):
                            loja['itens'].pop(i_idx)
                            st.rerun()

            if st.button("💾 Sincronizar Edição com a Nuvem", type="primary"):
                if supabase_client:
                    supabase_client.table("apreensoes").delete().eq("operacao_id", fisc_edit['operacao_id']).execute()
                    novos_dados = []
                    for loja in fisc_edit['lojas']:
                        for it in loja['itens']:
                            novos_dados.append({
                                "operacao_id": fisc_edit['operacao_id'], "data_hora": datetime.now().isoformat(),
                                "fiscal": st.session_state['nome_fiscal'], "loja": f"Loja {loja['numero']} - {loja['nome']}",
                                "categoria": it['Categoria'], "tipo": it['Tipo'], "produto": it['Produto'], 
                                "status": it['Status'], "cnpj": it['CNPJ Identificado'], "quantidade": it['Quantidade']
                            })
                    if novos_dados: supabase_client.table("apreensoes").insert(novos_dados).execute()
                    st.toast("✅ Edição sincronizada com sucesso!", icon="✅")

    # --- TELA 6: MONITORAMENTO ---
    elif menu == "Monitoramento (Logs)":
        st.title("👁️ Trilha de Auditoria (AgGrid Enterprise)")
        if st.button("🔄 Atualizar Trilha", type="secondary"): st.rerun()
            
        if supabase_client:
            try:
                resp = supabase_client.table("auditoria").select("*").order("data_hora", desc=True).execute()
                if resp.data:
                    df_logs = pd.DataFrame(resp.data)
                    df_logs['data_hora'] = pd.to_datetime(df_logs['data_hora']).dt.strftime('%d/%m/%Y %H:%M:%S')
                    df_logs = df_logs[['data_hora', 'fiscal', 'acao', 'detalhes']]
                    if HAS_AGGRID:
                        gb = GridOptionsBuilder.from_dataframe(df_logs)
                        gb.configure_pagination(paginationAutoPageSize=True, paginationPageSize=20)
                        gb.configure_default_column(filter=True, sortable=True)
                        AgGrid(df_logs, gridOptions=gb.build(), theme='streamlit', fit_columns_on_grid_load=True)
                    else: st.dataframe(df_logs, use_container_width=True)
                else: st.info("Nenhum registro encontrado.")
            except Exception as e: st.error("Erro ao carregar auditoria.")
        else: st.warning("Conecte ao Supabase para visualizar o monitoramento.")

def iniciar():
    if not st.session_state.get('autenticado'): tela_login()
    else: app()

if __name__ == "__main__":
    iniciar()
