import streamlit as st
import pandas as pd
from datetime import datetime
import io
import re
import copy
from fpdf import FPDF
from PIL import Image

try:
    from supabase import create_client, Client
    HAS_SUPABASE = True
except ImportError:
    HAS_SUPABASE = False

try:
    import pytesseract
    HAS_OCR = True
except ImportError:
    HAS_OCR = False

# ==========================================
# CONFIGURAÇÃO E TEMA
# ==========================================
st.set_page_config(page_title="GGTAB/ANVISA - Fiscalização", page_icon="🚭", layout="wide")

# ==========================================
# CONEXÃO SUPABASE & AUDITORIA
# ==========================================
@st.cache_resource
def init_supabase():
    if not HAS_SUPABASE: return None
    try:
        url: str = st.secrets["SUPABASE_URL"]
        key: str = st.secrets["SUPABASE_KEY"]
        return create_client(url, key)
    except Exception:
        return None

supabase_client = init_supabase()

def registrar_log(acao, detalhes):
    if supabase_client and st.session_state.get('nome_fiscal'):
        try:
            supabase_client.table("auditoria").insert({
                "data_hora": datetime.now().isoformat(),
                "fiscal": st.session_state['nome_fiscal'],
                "acao": acao,
                "detalhes": detalhes
            }).execute()
        except Exception: pass

# ==========================================
# BASE DE DADOS COMPLETA E CORRIGIDA
# ==========================================
DB_PRODUTOS_BASE = {
    "💨 DEF (Dispositivos Eletrônicos para Fumar)": {
        "Cigarros eletrônicos (Vapes e Pods)": {
            "Ignite (Pod Descartável)": "Ilegal/Sem CNPJ",
            "Elfbar (Pod Descartável)": "Ilegal/Sem CNPJ",
            "Waka (Pod Descartável)": "Ilegal/Sem CNPJ",
            "Lost Mary (Pod Descartável)": "Ilegal/Sem CNPJ",
            "NikBar (Pod Descartável)": "Ilegal/Sem CNPJ",
            "Life Pod": "Ilegal/Sem CNPJ",
            "Vaporesso (Aparelho/Mod)": "Ilegal/Sem CNPJ",
            "Smok (Aparelho/Mod)": "Ilegal/Sem CNPJ",
            "Voopoo (Aparelho/Mod)": "Ilegal/Sem CNPJ",
            "Geekvape (Aparelho/Mod)": "Ilegal/Sem CNPJ",
            "Uwell / Caliburn": "Ilegal/Sem CNPJ"
        },
        "Cigarros aquecidos ou tabaco aquecido": {
            "IQOS (Heets / Terea)": "Ilegal/Sem CNPJ",
            "Glo (Neo)": "Ilegal/Sem CNPJ",
            "Ploom (Evo)": "Ilegal/Sem CNPJ",
            "Jouz": "Ilegal/Sem CNPJ"
        },
        "Vaporizadores de ervas secas": {
            "G Pen (Grenco Science)": "Ilegal/Sem CNPJ",
            "Pax (Pax Labs)": "Ilegal/Sem CNPJ",
            "Mighty / Volcano (Storz & Bickel)": "Ilegal/Sem CNPJ",
            "Dynavap": "Ilegal/Sem CNPJ",
            "Zigg (King Vapo)": "Ilegal/Sem CNPJ",
            "Arizer": "Ilegal/Sem CNPJ"
        },
        "Produtos híbridos": {
            "Lil Solid (KT&G)": "Ilegal/Sem CNPJ",
            "Ploom Tech": "Ilegal/Sem CNPJ"
        },
        "Essências e Juices (Líquidos para DEF)": {
            "Nasty Juice": "Ilegal/Sem CNPJ",
            "Naked 100": "Ilegal/Sem CNPJ",
            "Zomo Vape (Juice)": "Ilegal/Sem CNPJ",
            "Magna": "Ilegal/Sem CNPJ",
            "BLVK Unicorn": "Ilegal/Sem CNPJ",
            "Dinner Lady": "Ilegal/Sem CNPJ",
            "Caravela Liquids": "Ilegal/Sem CNPJ"
        }
    },
    "🍂 TABACOS E DERIVADOS": {
        "🚬 Cigarros (Filtro/Kretek)": {
            "GRIFFE BLUE (BRIX SPECIAL TABACO BLEND LTDA)": "27.643.835/0001-16",
            "EL CRETEC CHERRY (CLEAN INDUSTRIA E COMERCIO DE CIGARROS LTDA)": "18.804.581/0001-80",
            "CLEAN CLK (CLEAN INDUSTRIA E COMERCIO DE CIGARROS LTDA)": "18.804.581/0001-80",
            "EL CRETEC MENTHOL (CLEAN INDUSTRIA E COMERCIO DE CIGARROS LTDA)": "18.804.581/0001-80",
            "EL PONCIO CRETEC CEREJA (CLEAN INDUSTRIA E COMERCIO DE CIGARROS LTDA)": "18.804.581/0001-80",
            "EL PONCIO CRETEC MENTA (CLEAN INDUSTRIA E COMERCIO DE CIGARROS LTDA)": "18.804.581/0001-80",
            "EL PONCIO GUDANG GARAM RED (CLEAN INDUSTRIA E COMERCIO DE CIGARROS LTDA)": "18.804.581/0001-80",
            "EL PONCIO GUDANG GARAM GREEN (CLEAN INDUSTRIA E COMERCIO DE CIGARROS LTDA)": "18.804.581/0001-80",
            "A2 (CONGO INDUSTRIA E COMERCIO DE CIGARROS IMPORTACAO E EXPORTACAO LTDA)": "12.011.627/0001-27",
            "LE7 (CONGO INDUSTRIA E COMERCIO DE CIGARROS IMPORTACAO E EXPORTACAO LTDA)": "12.011.627/0001-27",
            "NEW YORK (CONGO INDUSTRIA E COMERCIO DE CIGARROS IMPORTACAO E EXPORTACAO LTDA)": "12.011.627/0001-27",
            "SENAT (CONGO INDUSTRIA E COMERCIO DE CIGARROS IMPORTACAO E EXPORTACAO LTDA)": "12.011.627/0001-27",
            "EXPRESS SAN MARINO BLUE (DICINA IND. E COM., IMP. E EXP. DE TABACOS LTDA)": "10.742.854/0001-05",
            "EXPRESS SAN MARINO RED (DICINA IND. E COM., IMP. E EXP. DE TABACOS LTDA)": "10.742.854/0001-05",
            "OSCAR CLASSIC TRADITIONAL (DICINA IND. E COM., IMP. E EXP. DE TABACOS LTDA)": "10.742.854/0001-05",
            "VILA RICA SKY (DICINA IND. E COM., IMP. E EXP. DE TABACOS LTDA)": "10.742.854/0001-05",
            "VILA RICA SUN (DICINA IND. E COM., IMP. E EXP. DE TABACOS LTDA)": "10.742.854/0001-05",
            "XES ORIGINAL (DICINA IND. E COM., IMP. E EXP. DE TABACOS LTDA)": "10.742.854/0001-05",
            "X-LINT WHITE (DICINA IND. E COM., IMP. E EXP. DE TABACOS LTDA)": "10.742.854/0001-05",
            "BILLION (EBT - EMPRESA BRASILEIRA DE TABACO LTDA)": "44.133.360/0001-37",
            "WINDSOR (EBT - EMPRESA BRASILEIRA DE TABACO LTDA)": "44.133.360/0001-37",
            "EGIPT BLUE (IBC – INDÚSTRIA BRASILEIRA DE CIGARROS LTDA)": "20.901.675/0001-19",
            "EGIPT RED (IBC – INDÚSTRIA BRASILEIRA DE CIGARROS LTDA)": "20.901.675/0001-19",
            "US FOX BLUE (IBC – INDÚSTRIA BRASILEIRA DE CIGARROS LTDA)": "20.901.675/0001-19",
            "CAMEL BLUE INTERNATIONAL SINCE 1913 (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL COMPACT (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL COMPACT BLUE PREMIUM BLEND (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL COMPACT PEAR (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL KRETEK BERRY (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL KRETEK MENTHOL (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL DOUBLE MINT & RED (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL LEGEND BLUE (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL LEGEND YELLOW (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL MY BLUE (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL MY YELLOW (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL PURPLE BEACH (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL PURBLE BEACH X (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL RED DUNE (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL RED DUNE X (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL YELLOW INTERNATIONAL SINCE 1913 (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL YELLOW TROPICAL (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "CAMEL YELLOW TROPICAL X (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "DJARUM BLACK ICE (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "DJARUM BLACK JADE MENTHOL (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "DJARUM BLACK ORIGINAL (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "LA MENTHOL (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON AVANT XS BLUE (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON BLUE HAND SELECTED TOBACCO (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON BLUE SELECTED (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON CLASSIC HAND SELECTED TOBACCO (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON CLASSIC SELECTED (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON SELECT PURPLE MINT (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON SELECTED DOUBLE MENTHOL (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON SELECTED BLUEMIX (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON SELECTED PURPLEMIX (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON SLIMS RED (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON SILVER SELECTED (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON UNIQUE RED (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON XSTYLE BLUE (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON XSTYLE CASTER (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON XSTYLE RED (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "WINSTON XSTYLE SILVER (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "A SAMPOERNA KRETEK MENTHOL SELECT KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "A SAMPOERNA KRETEK MENTHOL SELECTED KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "A SAMPOERNA KRETEK SELECTED KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD ORIGINAL BLUE KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD ORIGINAL LABEL KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD REMIX BEATS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD REMIX FRESH MINT KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD REMIX SELECT (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD REMIX WILD (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD SILVER KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD TERRAS BRASILEIRAS SELECIONADO (ORANGE) (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD TERRAS BRASILEIRAS ORIGINAL AZUL (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD TERRAS BRASILEIRAS ORIGINAL LARANJA (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD TERRAS BRASILEIRAS SELECIONADO (BLUE) (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD TERRAS BRASILEIRAS SELECIONADO (SILVER) (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD TERRAS BRASILEIRAS TABACO SELECIONADO BLUE (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "CHESTERFIELD TERRAS BRASILEIRAS TABACO SELECIONADO ORIGINAL (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "HARMONY SELECIONADO BY LINEA (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "HARMONY SLIMS BY LUXOR (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "L&M BLUE LINE KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "L&M EVO KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "L&M FIRST CUT (BLUE) (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "L&M FIRST CUT (BLUE) TOBACCO (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "L&M FIRST CUT (RED) (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "L&M FIRST CUT (RED) TOBACCO (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "L&M FIRST CUT (SILVER) (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "L&M FORWARD (NEW BLACK) KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "L&M KRETEK (BLACK) KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO ADVANCE (BLACK) KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO ADVANCE FOREST (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO ADVANCE TROPICAL (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO BLUE SELECTION EST° 1908 (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO FILTER PLUS KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO FOREST FUSION (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO GOLD SELECTION EST° 1908 (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO GOLD (STRIPES) KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO ICE BURST MENTHOL KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO KRETEK MINT (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO (RED FWD) KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO RED SELECTION ESTº 1908 KS (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO SELECTION FOREST BREEZE ESTº 1908 (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO TROPICAL FUSION (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO VISTA DOUBLE BURST (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO VISTA DOUBLE FUSION (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "MARLBORO VISTA PURPLE MIX - (PHILIP MORRIS BRASIL INDÚSTRIA E COMÉRCIO LTDA.)": "04.041.933/0001-88",
            "PRIORI (PRIORI TABACOS INDÚSTRIA E COMÉRCIO LTDA)": "34.593.307/0001-65",
            "GIFT (QUALITY IN TABACOS IND. E COM. DE CIGARROS E IMPORTAÇÃO E EXPORTAÇÃO LTDA)": "11.816.308/0001-26",
            "GIFT RED SECOND EDITION (QUALITY IN TABACOS IND. E COM. DE CIGARROS E IMPORTAÇÃO E EXPORTAÇÃO LTDA)": "11.816.308/0001-26",
            "NEW OUTBACK SLIMS (QUALITY IN TABACOS IND. E COM. DE CIGARROS E IMPORTAÇÃO E EXPORTAÇÃO LTDA)": "11.816.308/0001-26",
            "DUNHILL BLUE BLEND 2.0 (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL CARLTON BLEND 2.0 (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL DOUBLE REFRESH (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL ICE REFRESH (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL INSIGNIA BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL INSIGNIA FULL RED (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL INSIGNIA RED (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL ON BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL ON ICE BOOST (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL ON ICE TROPIC (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL ON RED (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL ON SILVER (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL ST JAMES ST LONDON BLUE BLEND (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL ST JAMES ST LONDON CARLTON BLEND (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL TOBACCO OF LONDON LTD EST 1907 EVOQUE TABACO BLEND (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL VOYAGE DOUBLE REFRESH (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL VOYAGE ICE REFRESH (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "DUNHILL VOYAGE MIX REFRESH (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "HOLLYWOOD CORE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "HOLLYWOOD CORE BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "KENT BLUE SERIES (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "KENT MIX GREEN TWIST (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "KENT MIX PURPLE TWIST (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "KENT MIX RED TWIST (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "KENT PRO BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "KENT PRO RED (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "KENT PRO SILVER (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "KENT RED SERIES (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "KENT SILVER SERIES (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE AN AMERICAN ORIGINAL (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE BLUE AN AMERICAN ORIGINAL (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE BLUE BLEND LUCKIES SINCE 1871 (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE BLUE CLICK (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE BLUE R.A. PATTERSON FOUNDER ESTD 1871 (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE DOUBLE CLICK (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE DOUBLE FROST (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE FRESH DOUBLE ICE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE FRESH DOUBLE ICE X (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE FRESH ICE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE FRESH MINT X (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE FRESH WILD (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE ORIGINAL BLEND LUCKIES SINCE 1871 (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE PURPLE MIX (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE RED MIX (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE RED R.A. PATTERSON FOUNDER ESTD 1871 (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE TWIST MIX (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "LUCKY STRIKE WILD MIX (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS GLOBAL CONNECTIONS BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS GLOBAL CONNECTIONS SILVER (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON EST. 1890 LOUIS ROTHMAN ORIGINAL TOBACCO GLOBAL BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON EST. 1890 LOUIS ROTHMAN ORIGINAL TOBACCO GLOBAL RED (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 BLUE INTERNATIONAL (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 GLOBAL BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 GLOBAL RED (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 HAND-SELECTED TOBACCOS BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 HAND-SELECTED TOBACCOS CORE BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 HAND-SELECTED TOBACCOS KINGSIZE BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 HAND-SELECTED TOBACCOS KINGSIZE RED (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 HAND-SELECTED TOBACCOS KINGSIZE SILVER (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 HAND-SELECTED TOBACCOS RED (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 HAND-SELECTED TOBACCOS SILVER (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 ICE BOOST (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 INTERNATIONAL WORLDWIDE CLICK SENSE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 INTERNATIONAL WORLDWIDE DOUBLE CLICK (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 PURPLE BOOST (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 SENSES FRESH (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 SPHERE BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 TROPICAL BOOST (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 WHITE CLASSIC BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON 1890 WHITE CLASSIC RED (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON CORE BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON SERIES BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON SERIES CLICK PURPLE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON SERIES RED (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "ROTHMANS OF LONDON SIGNATURE BLUE (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "GF (VITORIA IMPORTAÇÃO, EXPORTAÇÃO, INDUSTRIA & COMERCIO DE TABACOS LTDA)": "18.559.637/0001-88",
            "WORLD STOP (VITORIA IMPORTAÇÃO, EXPORTAÇÃO, INDUSTRIA & COMERCIO DE TABACOS LTDA)": "18.559.637/0001-88"
        },
        "🕴️ Charutos": {
            "LOS 3 CATEDRATICOS DELÍCIAS ROBUSTO (ALCEMIRO FERREIRA DE BARROS - ME)": "12.791.254/0001-54",
            "PERCEVERANCIA NICARAGUA - TORO (APM COMERCIO, IMPORTAÇÃO E EXPORTAÇÃO DE FUMO LTDA)": "05.968.360/0001-03",
            "ARTURO FUENTE CHATEAU FUENTE (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "ARTURO FUENTE MAGNUM R VITOLA FIFTY-SIX (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "BRICK HOUSE TORO (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "FACTORY SMOKES ROBUSTO (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "JOYA DE NICARAGUA ANTAÑO CT TORO (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "JOYA DE NICARAGUA ANTAÑO CONSUL (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "JOYA DE NICARAGUA CABINETTA ROBUSTO (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "JOYA DE NICARAGUA CLASSICO ORIGINAL ROBUSTO (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "JOYA DE NICARAGUA MEDIO SIGLO TORO (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "NUB CONNECTICUT 460 (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "OLIVA SERIE G AGED CAMEROON DOUBLE ROBUSTO (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "OLIVIA SERIE V DOUBLE TORO (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "OLIVA SERIE V MELANIO Nº4 (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "PERLA DEL MAR ROBUSTO (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "QUORUM ROBUSTO (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "ROSALONES RESERVA R50 (BMCS COMERCIO IMPORTAÇÃO E EXPORTAÇÃO EIRELI – ME)": "24.259.866/0001-80",
            "GENTILI (CRISTINA D'ANGELO - COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO LTDA)": "40.585.474/0001-67",
            "PICHARDO RESERVA FAMILIAR SAN ANDRÉS (EDUARDO LLERENA HERNANDEZ)": "12.470.901/0001-26",
            "FLOR DE LA VEGA (BRAVOS-TORO) (E & M INTERNATIONAL IMPORTACAO E EXPORTACAO DE PRODUTOS DE TABACARIA LTDA ME)": "10.375.124/0001-05",
            "LEITE E ALVES ROBUSTO (FÁBRICA DE CHARUTOS LEITE E ALVES LTDA – ME)": "07.362.838/0001-74",
            "DON FERNANDO EXIGENTES (F E BENCOMO PEREZ ARTIGOS DE TABACARIA)": "08.890.797/0001-51",
            "7 PONTAS (HAVANA INDUSTRIA E COMÉRCIO DE FUMOS LIMITADA - ME)": "76.865.187/0001-58",
            "CARAVANA (HAVANA INDUSTRIA E COMÉRCIO DE FUMOS LIMITADA - ME)": "76.865.187/0001-58",
            "TALVIS CORONA (INDUSTRIA TABACOS DA BAHIA LTDA)": "05.816.263/0001-97",
            "LA CUBANITA (J&B IMPORTAÇÃO E EXPORTAÇÃO LTDA)": "32.340.714/0001-35",
            "JAMM CIGAR SUPER PREMIUM (JAMM CIGAR CHARUTOS LTDA)": "39.960.144/0001-25",
            "DON JORGE ROBUSTO (JORGE ESPINOSA CASTELLANOS LTDA)": "38.306.405/0001-25",
            "COHIBA ROBUSTO (MAREVA COMERCIALIZAÇÃO DE TABACO ME)": "25.370.137/0001-69",
            "LA GLORIA CUBANA (MAREVA COMERCIALIZAÇÃO DE TABACO ME)": "25.370.137/0001-69",
            "MONTECRISTO N. 4 (MAREVA COMERCIALIZAÇÃO DE TABACO ME)": "25.370.137/0001-69",
            "PARTAGAS SERIE D N.4 (MAREVA COMERCIALIZAÇÃO DE TABACO ME)": "25.370.137/0001-69",
            "ROMEO Y JULIETA MILLE FLEURS (MAREVA COMERCIALIZAÇÃO DE TABACO ME)": "25.370.137/0001-69",
            "CAFÉ CRÈME GRANDE I (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "CAFÉ CRÈME GRANDE II (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "CAO PILON ROBUSTO (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "DON DIEGO ROBUSTO (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "MACANUDO INSPIRADO (WHITE) ROBUSTO (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "PHILLIES TITAN (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "PHILLIES TITAN CHOCOLATE (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "PHILLIES TITAN PINK (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "REPOSADO 96 ESTATE BLEND ROBUSTO (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "VEGAFINA 1998 LA ROMANA 50 (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "VEGAFINA ROBUSTO (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "VDG SUMATRA Nº2 CLARO (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "SAN RAFFAEL CORONA (SAN GENARO INDUSTRIA E COMERCIO LTDA)": "23.664.538/0001-04",
            "SECONDS TORO (STJA GRAN HABANO CHARUTARIA LTDA)": "26.652.153/0001-07",
            "DON EMMANUEL ANUNNAKI KI (ZIGURATE IMPORTACAO E DISTRIBUICAO LTDA)": "52.126.566/0001-68",
            "DON BLEND GENIALES (Y.R. HERNANDEZ COMÉRCIO DE CHARUTOS - ME)": "23.159.448/0001-58"
        },
        "🌿 Fumo Desfiado": {
            "MIRAGE WHITE CREAM (BANES TABACOS & CO LTDA)": "59.212.133/0001-74",
            "TABEAR (BEAR OFFICIAL TABACOS LTDA)": "26.622.376/0001-21",
            "FUMO DESFIADO BELA FLOR (BELA FLOR INDUSTRIA E COMERCIO DE FUMOS LTDA)": "88.654.827/0001-60",
            "FUMOS LUAR (BELA FLOR INDUSTRIA E COMERCIO DE FUMOS LTDA)": "88.654.827/0001-60",
            "FUMO DESFIADO BOMBACO TRADICIONAL (BOMBACO PRODUTOS DE TABACO LTDA)": "35.472.366/0001-48",
            "STECKER AMARELINHO (COMERCIAL DE FUMOS BLEND LTDA)": "05.476.749/0001-23",
            "XORORÓ (COMERCIO E INDÚSTRIA DE FUMO ARAPIRACA LTDA – EPP)": "53.671.251/0001-64",
            "FUMO DESFIADO JURITI (COMÉRCIO E INDÚSTRIA DE FUMOS JAUENSE LTDA)": "55.817.217/0001-80",
            "CATOINHO (DISTRIBUIDORA DE FUMOS CATOINHO LTDA)": "55.428.288/0001-91",
            "DUBLIN ICE MINT TOBACCO (DUBLIN TABACOS LTDA)": "37.391.845/0001-65",
            "ZOMO (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "ALÍAR (HOPPE INDÚSTRIA E COMÉRCIO DE TABACOS LTDA)": "15.698.792/0001-97",
            "AMSTERDAM (HOPPE INDÚSTRIA E COMÉRCIO DE TABACOS LTDA)": "15.698.792/0001-97",
            "ACREMA BLEND (HBT INDÚSTRIA E COMÉRCIO DE TABACOS LTDA)": "18.044.630/0001-23",
            "HI TOBACCO GOLDEN VIRGINIA (HBT INDÚSTRIA E COMÉRCIO DE TABACOS LTDA)": "18.044.630/0001-23",
            "HI TOBACCO VIRGINIA BLEND (HBT INDÚSTRIA E COMÉRCIO DE TABACOS LTDA)": "18.044.630/0001-23",
            "RAINBOW GOLDEN BROWN (HBT INDÚSTRIA E COMÉRCIO DE TABACOS LTDA)": "18.044.630/0001-23",
            "RAINBOW SILVER BRIGHT (HBT INDÚSTRIA E COMÉRCIO DE TABACOS LTDA)": "18.044.630/0001-23",
            "TABAQUIN GOLDEN VIRGINIA (HBT INDÚSTRIA E COMÉRCIO DE TABACOS LTDA)": "18.044.630/0001-23",
            "FUMO DESFIADO BF (INDUSTRIA E COMERCIO DE FUMOS BEIJA FLOR LTDA)": "88.617.899/0001-37",
            "FUMO WILSON (INDÚSTRIA E COMÉRCIO DE FUMOS JATAI LTDA)": "01.693.647/0001-09",
            "FUMO SUPER GALO (INDUSTRIA E COMERCIO DE FUMOS SUPER GALO LTDA - EPP)": "05.418.580/0001-55",
            "REI DO ORIENTE MÉDIO (JOSÉ GILMAR MICHELS & CIA LTDA)": "89.461.131/0001-80",
            "ZEBÚ (JOSÉ GILMAR MICHELS & CIA LTDA)": "89.461.131/0001-80",
            "AMERICAN SPIRIT BLUE RYO (JTI PROCESSADORA DE TABACO DO BRASIL LTDA)": "03.334.170/0001-09",
            "LA REVOLUCIÓN GOLDEN VIRGINIA (LRV BRASIL INDÚSTRIA E COMERCIO E EXPORTAÇÃO DE TABACO LTDA)": "33.377.413/0001-49",
            "SLC DE OURO (MARCELO CERENTINI)": "17.425.086/0001-05",
            "TAHAS (NELMARA PORTO PREBIANCHI)": "42.819.542/0001-30",
            "JUNGLE BAUNILHA (NORTE PIONEIRO INDÚSTRIA E COMÉRCIO DE FUMOS EIRELI)": "34.443.602/0001-35",
            "JUNGLE CHOCOLATE (NORTE PIONEIRO INDÚSTRIA E COMÉRCIO DE FUMOS EIRELI)": "34.443.602/0001-35",
            "JUNGLE VIRGÍNIA (NORTE PIONEIRO INDÚSTRIA E COMÉRCIO DE FUMOS EIRELI)": "34.443.602/0001-35",
            "MUCHACHOS TRADICIONAL (NORTE PIONEIRO INDÚSTRIA E COMÉRCIO DE FUMOS EIRELI)": "34.443.602/0001-35",
            "YERBA (ORC BRASIL COMÉRCIO DE TABACARIA LTDA)": "29.373.215/0001-30",
            "QUEBEC (ORION TOBACCO INDUSTRIA E COMERCIO LTDA)": "12.821.901/0001-23",
            "MONTEVIDEO (PALAZZO TABACUM LTDA)": "23.095.277/0001-40",
            "DRUM ORIGINAL (RC PREMIUM COMERCIO IMPORTADORA E EXPORTADORA EIRELLI – EPP)": "17.121.200/0001-03",
            "DP TABACOS (REGIONAL TABACOS LTDA)": "14.952.190/0001-51",
            "SASSO TABACCOS BRASIL (RMS TABACOS BRASIL LTDA)": "37.327.231/0001-14",
            "FUMO SUL (SAN MARTIN FABRICAÇÃO DE TABACO LTDA)": "15.006.574/0001-44",
            "SANTORINI PREMIUM (SANTORINI COMERCIO DE TABACOS LTDA)": "47.245.842/0001-77",
            "SELVA (SLV INDUSTRIA E COMERCIO LTDA)": "49.229.504/0001-77",
            "FUMO PARA CIGARROS TREVO TRADICIONAL (SOUZA CRUZ LTDA)": "33.009.911/0001-39",
            "SASSO SESSION (STB SASSO TABACCOS BRASIL LTDA)": "37.327.231/0001-14",
            "VB TOBACO (STJA GRAN HABANO CHARUTARIA LTDA)": "26.652.153/0001-07",
            "MARAJÓ (SWISS SPIRIT INTERNATIONAL LTDA)": "18.750.908/0001-88",
            "FUMO PEÃO TRADICIONAL (TABACARIA GUANABARA LTDA EPP)": "78.402.013/0001-84",
            "TABACO DO VÉIO PIMENTA (TABACO DO VEIO PIMENTA LTDA)": "22.916.580/0001-02",
            "FINAMORE - GOLDEN VIRGINIA TOBACCO (TABACOS CISNE BRANCO FINAMORE LTDA – ME)": "12.389.368/0001-72",
            "FUMO DESFIADO CONQUISTADOR (TABACOS CONQUISTADOR LTDA)": "11.997.987/0001-87",
            "PUEBLO BLUE (TOBACCONIST COMERCIO DE TABACOS LTDA)": "06.863.253/0001-75",
            "PUEBLO CLASSIC (TOBACCONIST COMERCIO DE TABACOS LTDA)": "06.863.253/0001-75",
            "TOG (TOG BRASIL LTDA)": "50.485.254/0001-15",
            "MANDUPI (TONABE ARTIGOS DE HEADSHOP LTDA)": "49.593.350/0001-06",
            "TA NA MÃO (TONABE ARTIGOS DE HEADSHOP LTDA)": "49.593.350/0001-06",
            "ORIGINAL TABACO BRASIL (TRF INDUSTRIA TABACO LTDA)": "31.369.746/0001-09"
        },
        "🌾 Cigarro de Palha": {
            "PALHEIROS UNIVERSITHA TRADICIONAL (A L QUEIROZ INDUSTRIA DE PALHEIROS E SIMILARES LTDA)": "27.139.778/0001-32",
            "SANTROPEZ TRADICIONAL (BIFON & BIFON PALHEIROS E DERIVADOS DO TABACO LTDA)": "27.799.277/0001-82",
            "BROTHERS PAIOL (BROTHERS PAIOL FABRICA DE PRODUTOS ARTESANAIS LTDA)": "49.994.196/0001-76",
            "JC PALHEIROS (CLAUDIO DA SILVA DIAS)": "30.869.686/0001-12",
            "CRISTAL PALHEIRO (CRISTAL PALHEIROS FUMOS E COMÉRCIO DE PRODUTOS ARTESANAIS LTDA)": "33.626.845/0001-46",
            "PALHEIROS EMBAIXADOR TRADICIONAL (INDÚSTRIA E COMÉRCIO DE PALHEIROS EMBAIXADOR LTDA)": "40.730.684/0001-00",
            "PALHEIROS PAULISTINHA (INDUSTRIA E COMERCIO DE PALHEIROS PAULISTINHA)": "13.206.312/0001-06",
            "PALHEIROS PAULISTINHA MENTA (INDUSTRIA E COMERCIO DE PALHEIROS PAULISTINHA)": "13.206.312/0001-06",
            "PALHEIROS PAULISTINHA OURO (INDUSTRIA E COMERCIO DE PALHEIROS PAULISTINHA)": "13.206.312/0001-06",
            "PALHEIROS PAULISTINHA TRADICIONAL (INDUSTRIA E COMERCIO DE PALHEIROS PAULISTINHA)": "13.206.312/0001-06",
            "PALHEIRO JURITI SLIM (J2S TABACOS LTDA)": "52.083.832/0001-12",
            "PALHEIRO PANTANEIRO (J2S TABACOS LTDA)": "52.083.832/0001-12",
            "JA PALHEIRO (JA PALHEIROS LTDA)": "24.471.436/0001-27",
            "PF PALHEIROS DE FUMO (J.G CORREIA DA SILVA)": "44.060.506/0001-61",
            "JACK PAIOL’S ORIGINAL ULTRA PREMIUM (JOÃO RESENDE FILHO)": "28.528.287/0001-46",
            "PRADO PALHEIROS (JULIANA CAVATÃO)": "22.899.501/0001-94",
            "MANDELLE ORIGINAL BLEND (LR COMÉRCIO DE TABACOS LTDA)": "31.884.049/0001-88",
            "COYOTE (MINAS ARTEFATOS LTDA)": "27.072.327/0001-25",
            "COYOTE PALHEIROS PREMIUM (MINAS ARTEFATOS LTDA)": "27.072.327/0001-25",
            "PALHEIROS CANARINHO ORIGINAL (NEW INDUSTRIA E COMERCIO DE TABACOS LTDA)": "39.404.583/0001-51",
            "DIPALHA PALHEIROS (NORTE PIONEIRO INDÚSTRIA E COMÉRCIO DE FUMOS EIRELI)": "34.443.602/0001-35",
            "TIMBAL (NORTE PIONEIRO INDÚSTRIA E COMÉRCIO DE FUMOS EIRELI)": "34.443.602/0001-35",
            "TIMBAL MENTA (NORTE PIONEIRO INDÚSTRIA E COMÉRCIO DE FUMOS EIRELI)": "34.443.602/0001-35",
            "PIONEIRO EXTRA (NORTE PIONEIRO INDÚSTRIA E COMÉRCIO DE FUMOS EIRELI)": "34.443.602/0001-35",
            "PIONEIRO TRADICIONAL (NORTE PIONEIRO INDÚSTRIA E COMÉRCIO DE FUMOS EIRELI)": "34.443.602/0001-35",
            "PAERINHO (PAERINHO INDÚSTRIA E COMERCIO LTDA)": "04.857.318/0001-44",
            "PALHEIROS DOURADINHO OURO (PALHEIROS DOURADINHOS LTDA)": "26.084.455/0001-26",
            "PALHEIROS PIRACANJUBA (PALHEIROS PIRACANJUBA LTDA)": "25.057.001/0001-01",
            "PALHEIROS PIRACANJUBA OURO (PALHEIROS PIRACANJUBA LTDA)": "25.057.001/0001-01",
            "PALHEIROS TERRA TOMBADA TRADICIONAL (PALHEIROS TERRA TOMBADA LTDA)": "46.637.515/0001-06",
            "PORTO FARIA GOLD (PORTO FARIA LTDA - ME)": "03.221.399/0001-29",
            "PORTO FARIA PAULISTA (PORTO FARIA LTDA - ME)": "03.221.399/0001-29",
            "ROLO TABAK TRADICIONAL (ROLO TABAK COMERCIO E REPRESENTACAO LTDA)": "27.651.665/0001-11",
            "SOUZA PAIOL TRADICIONAL ORIGINAL (SOUZAPAIOL VASCONCELOS INDÚSTRIA E COMÉRCIO CIGARRO DE PALHA LTDA)": "32.956.729/0001-22",
            "PALHEIROS 3 LOBOS ORIGINAL (TL FABRICÃO DE PRODUTOS LTDA)": "34.099.121/0001-54",
            "YANKING (YANNKEE FÁBRICA DE CIGARROS DE PALHA LTDA)": "23.367.974/0001-03"
        },
        "🌬️ Fumo para Narguilé": {
            "NAY BLEND MANGA BANANA (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "NAY BLEND MANGO MELON (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "NAY BLEND PINEAPPLE GRAPE (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "NAY BLEND PINEAPPLE TWIST (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "NAY BUBBLE GRAPE (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "NAY CEREJA BLEND (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "NAY MARACUJA BLEND (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "NAY MELANCIA (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "NAY MINT (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "NAY RED BLEND FRAMBOESA & UVA (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "NAY SNOW (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "ZOMO MAX CHICLETE TUTTI FRUTTI (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "ZOMO MAX MAÇA VERDE (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "ZOMO MAX MELÃO (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "ZOMO MINT (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "ZOMO MIX BERRIES MINT (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "ZOMO PASSION LEMONADE (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "ZOMO STRONG MINT (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "ZOMO SWISS ALPS (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "ZOMO TWO APPLE BAHRAINI (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "ZOMO WATERMELON MINT (ELITE TRADE IMPORTAÇÃO E EXPORTAÇÃO EIRELI ME)": "27.839.998/0001-79",
            "BABOS 66 (LATIN TOBACCO FLAVOURS INDUSTRIA E COMERCIO DE TABACO LTDA)": "37.449.144/0001-30",
            "CHACAL TOBACCO BUBBA MINT (NAPOLES INDUSTRIA E COMERCIO LTDA)": "39.668.077/0001-70",
            "CHACAL TOBACCO BUBBA WATERMELON (NAPOLES INDUSTRIA E COMERCIO LTDA)": "39.668.077/0001-70",
            "CHACAL TOBACCO GRAPE (NAPOLES INDUSTRIA E COMERCIO LTDA)": "39.668.077/0001-70",
            "CHACAL TOBACCO STRAWBERRY (NAPOLES INDUSTRIA E COMERCIO LTDA)": "39.668.077/0001-70",
            "SNS TOBACCO ABSOLUT MINT (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "SNS TOBACCO MORANGO E MELANCIA ICE (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL BANANA TROPICAL (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL BERRY (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL FRESH 66 (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL BURLEY MINT (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL CHERRY (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL CORN MAGIC (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL FRESH LEMON (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL FRESH MELON (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL FRUTTI (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL GRAPE (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL HAPOCALYX MINT (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL JABUTICABA TROPICAL (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL MANGA TROPICAL (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL MIX DUAS GOIABAS (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL MIX DUAS MAÇÃS VERDES (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL MIX FRUTAS ROXAS (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL MIX FRUTAS VERDES (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL MIX FRUTAS AMARELAS (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL MIX MORANGO E LARANJA (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL MORANGO TROPICAL (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL SORVETE DE LIMÃO (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL SORVETE DE PISTACHE (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL WATERMELON BOMB (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL YELLOW (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ZGY BRASIL YOGURT (OTC COMERCIO E FABRICAÇÃO DE FUMOS LTDA)": "31.695.833/0001-48",
            "ADALYA ICE BON (PACTUAL COMÉRCIO E IMPORTAÇÃO LTDA)": "05.165.237/0001-46",
            "ADALYA 66 (PACTUAL COMÉRCIO E IMPORTAÇÃO LTDA)": "05.165.237/0001-46",
            "ADALYA SWISS (PACTUAL COMÉRCIO E IMPORTAÇÃO LTDA)": "05.165.237/0001-46",
            "ADALYA TWO MELON ICE (PACTUAL COMÉRCIO E IMPORTAÇÃO LTDA)": "05.165.237/0001-46",
            "ONA TOBACCO 66 (TURBRAS IMPORTACAO E EXPORTACAO LTD)": "51.094.844/0001-80",
            "ONA TOBACCO CALLISTA (TURBRAS IMPORTACAO E EXPORTACAO LTD)": "51.094.844/0001-80",
            "ONA TOBACCO COLA (TURBRAS IMPORTACAO E EXPORTACAO LTD)": "51.094.844/0001-80",
            "ONA TOBACCO DOMINIC (TURBRAS IMPORTACAO E EXPORTACAO LTD)": "51.094.844/0001-80",
            "ONA TOBACCO LEMON MINT (TURBRAS IMPORTACAO E EXPORTACAO LTD)": "51.094.844/0001-80",
            "ONA TOBACCO TWO APPLES (TURBRAS IMPORTACAO E EXPORTACAO LTD)": "51.094.844/0001-80"
        },
        "🪈 Fumo para Cachimbo": {
            "IRLANDEZ TRADICIONAL ORIGINAL (TABACOS CISNE BRANCO FINAMORE LTDA – ME)": "12.389.368/0001-72"
        }
    }
}

# Mescla os produtos base com os novos cadastrados na Nuvem
def obter_banco_atualizado():
    banco_dinamico = copy.deepcopy(DB_PRODUTOS_BASE)
    if supabase_client:
        try:
            resp = supabase_client.table('produtos_customizados').select('*').execute()
            for row in resp.data:
                cat, tipo, prod, cnpj = row['categoria'], row['tipo'], row['produto'], row['cnpj']
                if cat in banco_dinamico:
                    if tipo not in banco_dinamico[cat]:
                        banco_dinamico[cat][tipo] = {}
                    banco_dinamico[cat][tipo][prod] = cnpj
        except Exception: pass
    return banco_dinamico

def salvar_produto_nuvem(categoria, tipo, produto, cnpj, status):
    if supabase_client:
        try:
            resp = supabase_client.table('produtos_customizados').select('*').eq('produto', produto).execute()
            if not resp.data:
                supabase_client.table('produtos_customizados').insert({
                    "categoria": categoria,
                    "tipo": tipo,
                    "produto": produto,
                    "cnpj": cnpj,
                    "status": status
                }).execute()
                registrar_log("Novo Produto Cadastrado", f"O produto '{produto}' ({status}) foi adicionado à base.")
        except Exception: pass

DB_PRODUTOS = obter_banco_atualizado()

def get_cnpj_mapping():
    mapping = {}
    for cat, tipos in DB_PRODUTOS.items():
        for tipo, produtos in tipos.items():
            for prod, cnpj in produtos.items():
                cnpj_limpo = re.sub(r'\D', '', cnpj) 
                if len(cnpj_limpo) > 10: mapping[cnpj_limpo] = prod
    return mapping
CNPJ_TO_PRODUTO = get_cnpj_mapping()

# ==========================================
# FUNÇÕES CORE (PDF, EXCEL, OCR)
# ==========================================
def clean_text_for_pdf(text):
    if not text: return text
    return text.encode('latin-1', 'ignore').decode('latin-1')

def ler_cnpj_imagem(imagem_bytes):
    if not HAS_OCR: return None
    try:
        img = Image.open(io.BytesIO(imagem_bytes))
        texto = pytesseract.image_to_string(img)
        numeros = re.sub(r'\D', '', texto)
        for cnpj_banco in CNPJ_TO_PRODUTO.keys():
            if cnpj_banco in numeros: return cnpj_banco
        return None
    except Exception: return None

def obter_fundamentacao_legal(categoria, status):
    if "Propaganda" in categoria: return "RDC no 840/2023 e Lei 9.294/96 (Propaganda Irregular)"
    elif "DEF" in categoria: return "RDC no 855/2024 e Lei 6.437/77 (Comercializacao de DEF)"
    elif "Ilegal" in status or "Nao Registrado" in status: return "RDC no 896/2024 e Lei 6.437/77 (Produto Fumeiro Sem Registro)"
    else: return "Amostragem / RDC no 838/2023 (Fiscalizacao de Embalagem)"

def gerar_excel(fisc):
    flat_data = []
    for loja in fisc['lojas']:
        for item in loja['itens']:
            flat_item = item.copy()
            flat_item['Loja'] = f"Loja {loja['numero']} - {loja['nome']}"
            flat_data.append(flat_item)
    df = pd.DataFrame(flat_data)
    if not df.empty: df = df.drop(columns=['Foto 1 Bytes', 'Foto 2 Bytes'], errors='ignore')
    out = io.BytesIO()
    with pd.ExcelWriter(out, engine='openpyxl') as w:
        if df.empty: df.to_excel(w, index=False, sheet_name='Sem_Apreensoes')
        else:
            for lname in df['Loja'].unique():
                aba = clean_text_for_pdf(lname)
                aba = ''.join(c for c in aba if c.isalnum() or c.isspace() or c == '-').strip()[:31]
                if not aba: aba = "Loja"
                df[df['Loja'] == lname].to_excel(w, index=False, sheet_name=aba)
    return out.getvalue()

def gerar_pdf(fisc):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("helvetica", style="B", size=15)
    pdf.cell(0, 10, clean_text_for_pdf("Auto de Inspecao e Apreensao - GGTAB/ANVISA"), ln=True, align='C')
    pdf.set_font("helvetica", size=9)
    data_str = fisc['data_inicio'].strftime('%d/%m/%Y %H:%M:%S')
    cab = f"Operacao: {fisc.get('operacao_id', 'Local')} | Fiscal: {st.session_state['nome_fiscal']}"
    pdf.cell(0, 8, clean_text_for_pdf(cab), ln=True, align='C')
    pdf.line(10, 28, 200, 28)
    pdf.ln(8)
    
    if not fisc['lojas']: pdf.cell(0, 10, "Nenhuma loja fiscalizada nesta operacao.", ln=True)
    else:
        for loja in fisc['lojas']:
            pdf.set_font("helvetica", style="B", size=13)
            pdf.set_text_color(0, 51, 102)
            pdf.cell(0, 10, clean_text_for_pdf(f"Estabelecimento: Loja {loja['numero']} - {loja['nome']}"), ln=True)
            pdf.set_text_color(0, 0, 0)
            if not loja['itens']:
                pdf.set_font("helvetica", style="I", size=10)
                pdf.cell(0, 6, "Nenhum item apreendido.", ln=True)
                pdf.ln(4)
                continue
            for item in loja['itens']:
                pdf.set_font("helvetica", style="B", size=11)
                pdf.cell(0, 7, clean_text_for_pdf(f"Item: {item['Produto']} (Hora: {item['Hora']})"), ln=True)
                pdf.set_font("helvetica", size=10)
                pdf.cell(0, 6, clean_text_for_pdf(f"Categoria: {item['Categoria']} | Tipo: {item['Tipo']}"), ln=True)
                qtd_str = f"Qtd: {item['Quantidade']} und. | Status: {item['Status']}"
                if "Propaganda" in item['Categoria']: qtd_str = f"Marca: {item['Produto']} | Status: {item['Status']}"
                pdf.cell(0, 6, clean_text_for_pdf(qtd_str), ln=True)
                pdf.set_font("helvetica", style="B", size=10)
                pdf.cell(0, 6, clean_text_for_pdf(f"CNPJ Identificado: {item['CNPJ Identificado']}"), ln=True)
                fund = obter_fundamentacao_legal(item['Categoria'], item['Status'])
                pdf.set_font("helvetica", style="I", size=9)
                pdf.set_text_color(200, 0, 0) if "Ilegal" in item['Status'] else pdf.set_text_color(0, 100, 0)
                pdf.cell(0, 6, clean_text_for_pdf(f"Fundamentacao: {fund}"), ln=True)
                pdf.set_text_color(0, 0, 0) 
                
                foto1, foto2 = item.get('Foto 1 Bytes'), item.get('Foto 2 Bytes')
                if foto1 or foto2:
                    pdf.ln(2)
                    y_atual = pdf.get_y()
                    x_offset = 10
                    if y_atual > 230:
                        pdf.add_page()
                        y_atual = pdf.get_y()
                    if foto1: pdf.image(io.BytesIO(foto1), x=x_offset, y=y_atual, w=50); x_offset += 60 
                    if foto2: pdf.image(io.BytesIO(foto2), x=x_offset, y=y_atual, w=50)
                pdf.ln(55) 
                pdf.line(10, pdf.get_y(), 200, pdf.get_y())
                pdf.ln(4)
    return bytes(pdf.output())

# ==========================================
# INICIALIZAÇÃO E SESSÃO
# ==========================================
if 'tentativas_login' not in st.session_state: st.session_state['tentativas_login'] = 0
if 'autenticado' not in st.session_state: st.session_state['autenticado'] = False 
if 'nome_fiscal' not in st.session_state: st.session_state['nome_fiscal'] = ""
if 'historico_operacoes' not in st.session_state: st.session_state['historico_operacoes'] = []
if 'fisc_ativa' not in st.session_state: st.session_state['fisc_ativa'] = None
if 'loja_ativa' not in st.session_state: st.session_state['loja_ativa'] = None
if 'modo_daltonismo' not in st.session_state: st.session_state['modo_daltonismo'] = False

def tela_login():
    st.title("🚭 Portal de Fiscalização - GGTAB/CCTAB")
    st.markdown("---")
    if st.session_state['tentativas_login'] >= 10:
        st.error("❌ Acesso bloqueado por excesso de tentativas. Contate a TI.")
        return
    with st.form("form_login"):
        st.subheader("Acesso ao Servidor Único")
        usuario = st.text_input("Login")
        senha = st.text_input("Senha", type="password")
        nome = st.text_input("Seu Nome Completo (Para auditoria)")
        if st.form_submit_button("Entrar"):
            if usuario == "GGTAB" and senha == "CCTAB" and nome.strip() != "":
                st.session_state['autenticado'], st.session_state['nome_fiscal'], st.session_state['tentativas_login'] = True, nome.strip(), 0
                registrar_log("Login", "Acesso concedido ao sistema.")
                st.rerun()
            else:
                st.session_state['tentativas_login'] += 1
                st.error(f"❌ Inválido. {10 - st.session_state['tentativas_login']} tentativa(s) restantes.")

# ==========================================
# INTERFACE PRINCIPAL
# ==========================================
def app():
    global DB_PRODUTOS 
    DB_PRODUTOS = obter_banco_atualizado()
    
    st.sidebar.title("🏛️ GGTAB - CCTAB")
    st.sidebar.markdown(f"**Fiscal:** 👮 {st.session_state['nome_fiscal']}")
    
    menu = st.sidebar.radio("Navegação", [
        "📊 Dashboard Geral", 
        "🔍 Consulta e Cadastro", 
        "📝 Nova Fiscalização", 
        "📂 Fiscalizações Anteriores",
        "👁️ Monitoramento (Logs)"
    ])
    
    if st.session_state['fisc_ativa']:
        duracao = datetime.now() - st.session_state['fisc_ativa']['data_inicio']
        st.sidebar.metric(label="⏱️ Operação Ativa", value=f"{duracao.seconds//3600:02d}:{(duracao.seconds//60)%60:02d}:{duracao.seconds%60:02d}")
    
    st.sidebar.markdown("---")
    if supabase_client: st.sidebar.success("🟢 Nuvem Ativa (Supabase)")
    else: st.sidebar.error("🔴 Rodando Localmente")
    
    st.sidebar.markdown("---")
    if st.sidebar.button("Sair do Sistema"):
        registrar_log("Logout", "Usuário saiu do sistema.")
        st.session_state['autenticado'] = False
        st.rerun()

    # --- TELA 1: DASHBOARD ---
    if menu == "📊 Dashboard Geral":
        st.title("📊 Painel de Inteligência GGTAB")
        todas_operacoes = st.session_state['historico_operacoes'].copy()
        if st.session_state['fisc_ativa'] and st.session_state['fisc_ativa']['lojas']:
            todas_operacoes.append(st.session_state['fisc_ativa'])
            
        total_ops = len(todas_operacoes)
        total_lojas = sum(len(op['lojas']) for op in todas_operacoes)
        total_produtos = sum(item['Quantidade'] for op in todas_operacoes for l in op['lojas'] for item in l['itens'])
        total_ilegais = sum(item['Quantidade'] for op in todas_operacoes for l in op['lojas'] for item in l['itens'] if "Ilegal" in item['Status'] or "Prop" in item['Categoria'])
        
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Operações", total_ops)
        c2.metric("Lojas Auditadas", total_lojas)
        c3.metric("Itens Totais", total_produtos)
        c4.metric("Itens Ilegais", total_ilegais, delta="Atenção", delta_color="inverse")
        st.markdown("---")
        st.info("O sistema está sincronizado com o banco de dados oficial e customizado da nuvem.")

    # --- TELA 2: CONSULTA E CADASTRO ---
    elif menu == "🔍 Consulta e Cadastro":
        st.title("🗃️ Gestão de Produtos (Base ANVISA + Customizada)")
        aba_consulta, aba_cadastro = st.tabs(["🔍 Consultar Existentes", "➕ Cadastrar Novo Produto"])
        
        with aba_consulta:
            termo = st.text_input("Digite a marca, tipo ou CNPJ para buscar:").lower()
            if termo:
                resultados = []
                for cat, tipos in DB_PRODUTOS.items():
                    for tipo, produtos in tipos.items():
                        for prod, cnpj in produtos.items():
                            if termo in prod.lower() or termo in cnpj.lower() or termo in tipo.lower():
                                status_base = "✅ Regular" if "Ilegal" not in cnpj else "❌ Ilegal (DEF)"
                                resultados.append({"Categoria": cat, "Tipo": tipo, "Produto": prod, "CNPJ": cnpj, "Status": status_base})
                if resultados:
                    st.dataframe(pd.DataFrame(resultados), use_container_width=True)
                else: st.warning("Produto não encontrado na base unificada.")
                
        with aba_cadastro:
            st.markdown("Cadastre permanentemente um novo produto (Regular recém-aprovado ou nova marca Ilegal) para que todos os fiscais possam utilizá-lo.")
            with st.form("form_cadastro_produto"):
                c1, c2 = st.columns(2)
                cat_cad = c1.selectbox("Categoria Macro", ["Selecione..."] + list(DB_PRODUTOS.keys()))
                
                if cat_cad != "Selecione...":
                    tipos_existentes = list(DB_PRODUTOS[cat_cad].keys()) + ["+ Criar Novo Tipo"]
                    tipo_cad = c2.selectbox("Tipo de Produto", ["Selecione..."] + tipos_existentes)
                    if tipo_cad == "+ Criar Novo Tipo": 
                        tipo_cad = st.text_input("Nome do Novo Tipo")
                else:
                    tipo_cad = c2.selectbox("Tipo de Produto", ["Aguardando Categoria..."])

                c3, c4, c5 = st.columns([2, 1, 1])
                prod_cad = c3.text_input("Nome Comercial da Marca/Produto")
                cnpj_cad = c4.text_input("CNPJ (Se houver)")
                status_cad = c5.selectbox("Status Fixo", ["Ilegal / Não Registrado", "✅ Regular (Registrado)"])
                
                if st.form_submit_button("Salvar no Banco de Dados Global", type="primary"):
                    if cat_cad != "Selecione..." and tipo_cad != "Aguardando Categoria..." and prod_cad and tipo_cad:
                        salvar_produto_nuvem(cat_cad, tipo_cad, prod_cad, cnpj_cad if cnpj_cad else "Não Informado", status_cad)
                        st.success(f"'{prod_cad}' adicionado ao banco com sucesso! Ele já aparecerá nas próximas fiscalizações.")
                    else: st.error("Preencha corretamente a Categoria, o Tipo e o Nome do produto.")

    # --- TELA 3: NOVA FISCALIZAÇÃO ---
    elif menu == "📝 Nova Fiscalização":
        st.title("📝 Registro de Operação")
        
        if not st.session_state['fisc_ativa']:
            if st.button("▶️ Iniciar Nova Fiscalização", type="primary"):
                op_id = f"OP-{len(st.session_state['historico_operacoes']) + 1}-{datetime.now().strftime('%Y%m%d%H%M')}"
                st.session_state['fisc_ativa'] = {"id": op_id, "operacao_id": op_id, "data_inicio": datetime.now(), "lojas": []}
                registrar_log("Operação Iniciada", f"Criou a operação {op_id}")
                st.rerun()
            return
            
        st.caption(f"Operação Ativa: {st.session_state['fisc_ativa']['operacao_id']}")
        
        if not st.session_state['loja_ativa']:
            with st.form("form_nova_loja"):
                st.subheader("📍 Entrar em Estabelecimento")
                c1, c2 = st.columns([1, 3])
                n_loja = c1.number_input("Nº da Loja", min_value=1)
                nome_loja = c2.text_input("Endereço/Nome Fantasia")
                if st.form_submit_button("Iniciar Auditoria"):
                    if nome_loja.strip():
                        st.session_state['loja_ativa'] = {"numero": n_loja, "nome": nome_loja, "itens": []}
                        st.rerun()
            
            if st.session_state['fisc_ativa']['lojas']:
                st.markdown("---")
                if st.button("🏁 Finalizar Fiscalização Total e Salvar na Nuvem", type="primary"):
                    fisc_atual = st.session_state['fisc_ativa']
                    if supabase_client:
                        dados = []
                        for loja in fisc_atual['lojas']:
                            for it in loja['itens']:
                                dados.append({
                                    "operacao_id": fisc_atual['operacao_id'],
                                    "data_hora": datetime.now().isoformat(),
                                    "fiscal": st.session_state['nome_fiscal'],
                                    "loja": f"Loja {loja['numero']} - {loja['nome']}",
                                    "categoria": it['Categoria'], "tipo": it['Tipo'],
                                    "produto": it['Produto'], "status": it['Status'],
                                    "cnpj": it['CNPJ Identificado'], "quantidade": it['Quantidade']
                                })
                        if dados:
                            supabase_client.table("apreensoes").insert(dados).execute()
                            registrar_log("Operação Finalizada", f"Salvou {len(dados)} itens da {fisc_atual['operacao_id']} na nuvem.")
                    
                    st.session_state['historico_operacoes'].append(fisc_atual)
                    st.session_state['fisc_ativa'] = None
                    st.success("Dados enviados com sucesso!")
                    st.rerun()
            return

        loja = st.session_state['loja_ativa']
        st.subheader(f"🏬 Loja {loja['numero']} - {loja['nome']}")
        
        with st.expander("📦 ADICIONAR ITEM À LOJA", expanded=True):
            cat_macro = st.selectbox("Categoria Macro", ["Selecione...", "💨 DEF (Dispositivos Eletrônicos para Fumar)", "🍂 TABACOS E DERIVADOS", "📢 Propaganda Irregular"])
            
            if cat_macro == "📢 Propaganda Irregular":
                m_prop = st.text_input("Marca Anunciada")
                metodo_foto = st.radio("Foto da Propaganda:", ["📸 Tirar Foto na Hora", "📁 Anexar Arquivo"], horizontal=True)
                foto_bytes = None
                if metodo_foto == "📸 Tirar Foto na Hora":
                    foto = st.camera_input("Foto")
                else:
                    foto = st.file_uploader("Anexar Foto", type=["jpg", "png", "jpeg"])
                if foto: foto_bytes = foto.getvalue()

                if st.button("Confirmar Propaganda"):
                    loja['itens'].append({
                        "Categoria": "Propaganda Irregular", "Tipo": "Propaganda", 
                        "Produto": m_prop or "N/I", "Status": "Ilegal", 
                        "CNPJ Identificado": "N/A", "Quantidade": 1, 
                        "Hora": datetime.now().strftime('%H:%M:%S'),
                        "Foto 1 Bytes": foto_bytes, "Foto 2 Bytes": None
                    })
                    st.rerun()
                    
            elif cat_macro != "Selecione...":
                is_def = "DEF" in cat_macro
                tipos = ["Selecione..."] + list(DB_PRODUTOS[cat_macro].keys()) + (["⚠️ OUTRO TIPO (Salvar na Nuvem)"] if not is_def else [])
                tipo_prod = st.selectbox("Tipo de Produto", tipos)
                
                if tipo_prod != "Selecione...":
                    is_novo = "⚠️" in tipo_prod
                    if is_novo: 
                        prod = "Novo"
                    else:
                        prods = ["Selecione..."] + list(DB_PRODUTOS[cat_macro][tipo_prod].keys()) + ["⚠️ OUTRA MARCA (Salvar na Nuvem)"]
                        prod = st.selectbox("Busque o Produto", prods)
                    
                    if prod != "Selecione...":
                        qtd = st.number_input("Quantidade (Unidades/Maços)", min_value=1)
                        f1_bytes, f2_bytes = None, None
                        
                        st.markdown("**Captura de Evidências Fotográficas (Apenas PDF)**")
                        metodo_foto = st.radio("Inserção de Fotos:", ["📸 Câmera", "📁 Arquivos"], horizontal=True)
                        col_f1, col_f2 = st.columns(2)
                        
                        if metodo_foto == "📸 Câmera":
                            f1 = col_f1.camera_input("1 - Embalagem Frontal")
                            f2 = col_f2.camera_input("2 - Lote / CNPJ")
                        else:
                            f1 = col_f1.file_uploader("1 - Embalagem Frontal", type=["jpg", "png", "jpeg"])
                            f2 = col_f2.file_uploader("2 - Lote / CNPJ", type=["jpg", "png", "jpeg"])
                            
                        if f1: f1_bytes = f1.getvalue()
                        if f2: f2_bytes = f2.getvalue()

                        # Robô OCR
                        cnpj_extraido = ""
                        if f2 and HAS_OCR and st.button("🤖 Tentar Auto-Preencher CNPJ (OCR)"):
                            cnpj_lido = ler_cnpj_imagem(f2_bytes)
                            if cnpj_lido:
                                st.success(f"CNPJ Encontrado na foto!")
                                cnpj_extraido = cnpj_lido
                            else:
                                st.warning("Nenhum CNPJ detectado com clareza. Digite manualmente.")

                        if is_novo or "⚠️" in prod:
                            c1, c2 = st.columns(2)
                            n_novo = c1.text_input("Nome da Nova Marca/Produto")
                            c_novo = c2.text_input("CNPJ (Opcional)", value=cnpj_extraido)
                            t_novo = st.text_input("Tipo Específico (Opcional)", value=tipo_prod if not is_novo else "")
                            
                            if st.button("➕ Confirmar Inserção e Salvar no Banco Global"):
                                nome_final = n_novo if n_novo else "Produto Ilegal S/ Nome"
                                cnpj_final = c_novo if c_novo else "Sem CNPJ"
                                tipo_final = t_novo if t_novo else "Outros"
                                status_final = "Ilegal/Apreensão" if is_def or is_novo else "Regular"
                                
                                salvar_produto_nuvem(cat_macro, tipo_final, nome_final, cnpj_final, status_final)
                                
                                cat_limpa = cat_macro.replace("💨 ", "").replace("🍂 ", "").replace("📢 ", "")
                                tipo_limpo = tipo_final.replace("🚬 ", "").replace("🕴️ ", "").replace("🌿 ", "").replace("🌾 ", "").replace("🌬️ ", "").replace("🪈 ", "")
                                
                                loja['itens'].append({
                                    "Categoria": cat_limpa, "Tipo": tipo_limpo, 
                                    "Produto": nome_final, "Status": status_final, 
                                    "CNPJ Identificado": cnpj_final, "Quantidade": qtd, 
                                    "Hora": datetime.now().strftime('%H:%M:%S'),
                                    "Foto 1 Bytes": f1_bytes, "Foto 2 Bytes": f2_bytes
                                })
                                st.rerun()
                        else:
                            # Produto já existente no banco local/nuvem
                            if st.button("➕ Confirmar Inserção"):
                                cnpj_banco = DB_PRODUTOS[cat_macro][tipo_prod][prod]
                                status_banco = "Regular" if "Ilegal" not in cnpj_banco else "Ilegal"
                                
                                cat_limpa = cat_macro.replace("💨 ", "").replace("🍂 ", "").replace("📢 ", "")
                                tipo_limpo = tipo_prod.replace("🚬 ", "").replace("🕴️ ", "").replace("🌿 ", "").replace("🌾 ", "").replace("🌬️ ", "").replace("🪈 ", "")

                                loja['itens'].append({
                                    "Categoria": cat_limpa, "Tipo": tipo_limpo, 
                                    "Produto": prod, "Status": status_banco, 
                                    "CNPJ Identificado": cnpj_banco, "Quantidade": qtd, 
                                    "Hora": datetime.now().strftime('%H:%M:%S'),
                                    "Foto 1 Bytes": f1_bytes, "Foto 2 Bytes": f2_bytes
                                })
                                st.rerun()

        if loja['itens']:
            df_loja = pd.DataFrame(loja['itens']).drop(columns=['Foto 1 Bytes', 'Foto 2 Bytes'], errors='ignore')
            st.dataframe(df_loja, use_container_width=True)
            
        if st.button("🔒 Fechar Esta Loja"):
            st.session_state['fisc_ativa']['lojas'].append(st.session_state['loja_ativa'])
            st.session_state['loja_ativa'] = None
            st.rerun()

    # --- TELA 4: EDIÇÃO DE FISCALIZAÇÕES ---
    elif menu == "📂 Fiscalizações Anteriores":
        st.title("📂 Histórico e Edição Avançada")
        st.markdown("Selecione uma operação para gerar relatórios ou editá-la. **Nota:** Alterar itens aqui e salvar sincronizará a versão corrigida com a Nuvem.")
        
        ops = st.session_state['historico_operacoes']
        if not ops: st.info("Nenhuma operação concluída na sessão.")
        else:
            op_dict = {f"{op['operacao_id']} - {op['data_inicio'].strftime('%d/%m %H:%M')}": i for i, op in enumerate(ops)}
            escolha = st.selectbox("Selecione a Operação:", list(op_dict.keys()))
            idx = op_dict[escolha]
            fisc_edit = ops[idx]
            
            c_rel, c_edit, c_del = st.columns([2, 2, 2])
            c_rel.download_button("📊 Baixar Excel Atualizado", data=gerar_excel(fisc_edit), file_name=f"{fisc_edit['operacao_id']}.xlsx", use_container_width=True)
            c_edit.download_button("📄 Baixar PDF Atualizado", data=gerar_pdf(fisc_edit), file_name=f"{fisc_edit['operacao_id']}.pdf", type="primary", use_container_width=True)
            
            if c_del.button("🗑️ Excluir Operação Inteira", use_container_width=True):
                if supabase_client:
                    try:
                        supabase_client.table("apreensoes").delete().eq("operacao_id", fisc_edit['operacao_id']).execute()
                        registrar_log("Exclusão de Operação", f"Excluiu a {fisc_edit['operacao_id']}")
                    except Exception: pass
                st.session_state['historico_operacoes'].pop(idx)
                st.success("Operação excluída com sucesso!")
                st.rerun()
            
            st.markdown("### Lojas e Itens (Modo Edição)")
            for l_idx, loja in enumerate(fisc_edit['lojas']):
                with st.expander(f"🏬 Loja {loja['numero']} - {loja['nome']} (Contém {len(loja['itens'])} itens)", expanded=True):
                    # Editar Itens Existentes
                    for i_idx, item in enumerate(loja['itens']):
                        c1, c2, c3, c4 = st.columns([3, 1, 2, 1])
                        n_prod = c1.text_input(f"Produto #{i_idx+1}", value=item['Produto'], key=f"p_{idx}_{l_idx}_{i_idx}")
                        n_qtd = c2.number_input(f"Qtd", value=item['Quantidade'], key=f"q_{idx}_{l_idx}_{i_idx}", min_value=1)
                        n_st = c3.text_input(f"Status", value=item['Status'], key=f"s_{idx}_{l_idx}_{i_idx}")
                        
                        if c4.button("❌ Del", key=f"d_{idx}_{l_idx}_{i_idx}"):
                            loja['itens'].pop(i_idx)
                            st.rerun()
                        item['Produto'], item['Quantidade'], item['Status'] = n_prod, n_qtd, n_st

                    # Seletor idêntico à Nova Fiscalização para Adicionar Item Esquecido
                    st.markdown("#### ➕ Adicionar Item Esquecido nesta Loja")
                    c_cat, c_tipo, c_prod = st.columns(3)
                    add_cat = c_cat.selectbox("Categoria", ["Selecione...", "💨 DEF (Dispositivos Eletrônicos para Fumar)", "🍂 TABACOS E DERIVADOS", "📢 Propaganda Irregular"], key=f"add_cat_{idx}_{l_idx}")
                    
                    if add_cat == "📢 Propaganda Irregular":
                        m_prop = c_tipo.text_input("Marca Anunciada", key=f"add_prop_{idx}_{l_idx}")
                        if c_prod.button("➕ Inserir Propaganda", key=f"btn_prop_{idx}_{l_idx}"):
                            loja['itens'].append({"Categoria": "Propaganda Irregular", "Tipo": "Propaganda", "Produto": m_prop or "N/I", "Status": "Ilegal", "CNPJ Identificado": "N/A", "Quantidade": 1, "Hora": datetime.now().strftime('%H:%M:%S'), "Foto 1 Bytes": None, "Foto 2 Bytes": None})
                            st.rerun()
                    elif add_cat != "Selecione...":
                        tipos_add = ["Selecione..."] + list(DB_PRODUTOS[add_cat].keys())
                        add_tipo = c_tipo.selectbox("Tipo", tipos_add, key=f"add_tipo_{idx}_{l_idx}")
                        if add_tipo != "Selecione...":
                            prods_add = ["Selecione..."] + list(DB_PRODUTOS[add_cat][add_tipo].keys())
                            add_prod = c_prod.selectbox("Produto", prods_add, key=f"add_prod_{idx}_{l_idx}")
                            if add_prod != "Selecione...":
                                c_qtd, c_btn = st.columns([1, 3])
                                add_qtd = c_qtd.number_input("Quantidade", min_value=1, key=f"add_qtd_{idx}_{l_idx}")
                                if c_btn.button("➕ Confirmar Inserção", key=f"btn_add_{idx}_{l_idx}"):
                                    cnpj_add = DB_PRODUTOS[add_cat][add_tipo][add_prod]
                                    status_add = "Regular" if "Ilegal" not in cnpj_add else "Ilegal/Apreensão"
                                    
                                    cat_limpa = add_cat.replace("💨 ", "").replace("🍂 ", "").replace("📢 ", "")
                                    tipo_limpo = add_tipo.replace("🚬 ", "").replace("🕴️ ", "").replace("🌿 ", "").replace("🌾 ", "").replace("🌬️ ", "").replace("🪈 ", "")
                                    
                                    loja['itens'].append({
                                        "Categoria": cat_limpa, 
                                        "Tipo": tipo_limpo, 
                                        "Produto": add_prod, 
                                        "Status": status_add, 
                                        "CNPJ Identificado": cnpj_add, 
                                        "Quantidade": add_qtd, 
                                        "Hora": datetime.now().strftime('%H:%M:%S'),
                                        "Foto 1 Bytes": None, "Foto 2 Bytes": None
                                    })
                                    st.rerun()
            
            if st.button("💾 Salvar Alterações desta Operação na Nuvem", type="primary"):
                if supabase_client:
                    supabase_client.table("apreensoes").delete().eq("operacao_id", fisc_edit['operacao_id']).execute()
                    novos_dados = []
                    for loja in fisc_edit['lojas']:
                        for it in loja['itens']:
                            novos_dados.append({
                                "operacao_id": fisc_edit['operacao_id'], "data_hora": datetime.now().isoformat(),
                                "fiscal": st.session_state['nome_fiscal'], "loja": f"Loja {loja['numero']} - {loja['nome']}",
                                "categoria": it['Categoria'], "tipo": it['Tipo'], "produto": it['Produto'], 
                                "status": it['Status'], "cnpj": it['CNPJ Identificado'], "quantidade": it['Quantidade']
                            })
                    if novos_dados: supabase_client.table("apreensoes").insert(novos_dados).execute()
                    registrar_log("Edição de Operação", f"Editou e sincronizou a {fisc_edit['operacao_id']}")
                    st.success("Operação atualizada na nuvem com sucesso!")

    # --- TELA 5: MONITORAMENTO (NOVA) ---
    elif menu == "👁️ Monitoramento (Logs)":
        st.title("👁️ Trilha de Auditoria do Sistema")
        st.markdown("Visualização de eventos, cadastros e edições em tempo real na nuvem.")
        if st.button("🔄 Atualizar Trilha"): st.rerun()
        
        if supabase_client:
            try:
                resp = supabase_client.table("auditoria").select("*").order("data_hora", desc=True).execute()
                if resp.data:
                    df_logs = pd.DataFrame(resp.data)
                    df_logs['data_hora'] = pd.to_datetime(df_logs['data_hora']).dt.strftime('%d/%m/%Y %H:%M:%S')
                    df_logs = df_logs[['data_hora', 'fiscal', 'acao', 'detalhes']]
                    st.dataframe(df_logs, use_container_width=True)
                else: st.info("Nenhum registro de auditoria encontrado ainda.")
            except Exception as e: st.error("Erro ao carregar auditoria.")
        else: st.warning("Conecte ao Supabase para visualizar o monitoramento global.")

def iniciar():
    if not st.session_state.get('autenticado'): tela_login()
    else: app()

if __name__ == "__main__":
    iniciar()